--  >>>>>>>>>>>>>BASIC SQL ASSIGNMENT >>>>>>

-- 1) WHAT IS SEQUEL AND EXPLAIN HISTORY OF SEQUEL ?
-- 2) EXPLAIN DATA WITH EXAMPLE
-- 3) WHAT IS DATABASE  AND EXPLAIN IT ?
-- 4) WHAT DOES DBMS AND RDBMS EXPLAIN WITH DIFFERENCES ?
-- 5) EXPLAIN THE RULES OF AN E.F CODD ?
-- 6) WHAT IS DATATYPE AND EXPLAIN ALL THE DATATYPES WITH SYNTAX ?
-- 7) DIFFERENCES BETWEEN CHAR AND VARCHAR ?
-- 8) EXPLAIN CONSTRAINTS WITH SYNTAX FOR EACH CONSTRAINTS ?
-- 9) DIFFERENCES BETWEEN PRIMARY KEY AND FOREIGN KEY 
-- 10) DIFFERENCES BETWEEN UNIQUE AND DISTINCT ?







-- >>>>>>> QUERIES ON PROJECTION >>>>>>>>>>

PROMPT SAL AND EMPLOYEE NAME FROM EMP TABLE;
select sal, ename from emp;

PROMPT NAME, DEPTNO AND JOB FROM EMP TABLE;
select ename, deptno, job from emp;

PROMPT HIREDATE AND DEPTNO FOR ALL EMPLOYEES;
select hiredate, deptno from emp;

PROMPT MGR AND EMPNO FROM EMP TABLE;
select mgr, empno from emp;

PROMPT ALL DETAILS OF ALL EMPLOYEES;
select * from emp;

PROMPT DEPARTMENT NAME FROM DEPT TABLE;
select dname from dept;

PROMPT LOC FROM DEPT TABLE;
select loc from dept;

PROMPT DEPTNO AND LOC FROM DEPT TABLE;
select deptno, loc from dept;

PROMPT ALL DETAILS OF DEPT TABLE;
select * from dept;

PROMPT DIFFERENT JOBS PRESENT IN EMP TABLE;
select distinct job from emp;

PROMPT ENAME AND SAL WITHOUT REPEATED RECORDS;
select distinct ename, sal from emp;

PROMPT HIREDATE AND SAL WITHOUT REPEATED RECORDS;
select distinct hiredate, sal from emp;

PROMPT JOB, SAL AND DEPTNO WITHOUT REPEATED RECORDS;
select distinct job, sal, deptno from emp;

PROMPT ALL DETAILS WITHOUT REPEATED RECORDS;
select distinct * from emp;

PROMPT ANNUAL SALARY FOR ALL EMPLOYEES;
select ename, sal*12  asalary from emp;

PROMPT HALF TERM SALARY FOR ALL EMPLOYEES;
select ename, sal/2  halfsal from emp;

PROMPT ENAME AND ANNUAL SALARY;
select ename, sal*12  asalary from emp;

PROMPT DEPTNO, JOB AND SAL WITH 10% HIKE;
select deptno, job, sal*1.10  salhike from emp;

PROMPT ALL DETAILS WITH ANNUAL SALARY;
select emp.*, sal*12 asalary from emp;

PROMPT 31) ALL THE DETAILS OF EMPLOYEES ALONG WITH 10% HIKE IN ANNUAL SALARY;
select emp.*, sal*12*1.10  hikesalary from emp;

PROMPT 32) SAL, ANNUAL SALARY, HALF TERM SALARY AND QUARTER TERM SALARY FOR ALL EMPLOYEES;
select sal, sal*12  asalary, (sal*12)/2  halsalary, (sal*12)/4  quartersalary from emp;

PROMPT 33) ANNUAL SALARY WITH 20% DEDUCTION FOR ALL EMPLOYEES;
select sal*12*0.80 asaldeduction from emp;

PROMPT 34) ALL DETAILS ALONG WITH 100 RS PENALTY FOR ALL EMPLOYEES;
select emp.*, sal-100  salpenalty from emp;

PROMPT 35) TOTAL SALARY NEEDED TO PAY FOR EACH EMPLOYEE;
select ename, sal   totalsalary from emp;

PROMPT 36) ANNUAL SALARY AND HALF TERM SALARY WITH ALIAS NAME;
select sal*12  asalary, (sal*12)/2  halfsalary from emp;

PROMPT 37) ALL DETAILS WITH 12% HIKE IN ANNUAL SALARY;
select emp.*, sal*12*1.12  hikesalary from emp;

PROMPT 38) JOB AS DESIGNATION, HIREDATE AS JOINING DATE, MGR AS REPORTING MANAGER;
select job as designation, hiredate  joiningdate, mgr  reporting_manager from emp;

PROMPT 39) JOB WITH DEPTNO USING ALIAS DESIGNATION AND DNO;
select job as designation, deptno  dno from emp;

PROMPT 40) ALL DETAILS WITH 50 RS HIKE IN SALARY AS BONUS;
select emp.*, sal+50  bonus from emp;

PROMPT 41 ) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHOSE SALARY IS MORE THEN 1000 ?;
select * from emp where sal > 1000;

PROMPT 42) ENAME AND SALARY FOR EMPLOYEES WHOSE DEPTNO IS 20;
select ename, sal from emp where deptno = 20;

PROMPT 43) JOB AND DEPTNO OF EMPLOYEES WORKING AS MANAGER;
select job, deptno from emp where job = 'manager';

PROMPT 44) ALL DETAILS OF EMPLOYEE WHOSE NAME IS KING;
select * from emp where ename = 'king';

PROMPT 45) NAME AND HIREDATE OF EMPLOYEES HIRED ON 01-JAN-81;
select ename, hiredate from emp where hiredate = '01-jan-81';

PROMPT 46) HIREDATE AND DEPTNO OF EMPLOYEES HIRED AFTER 1981;
select hiredate, deptno from emp where hiredate > '31-dec-81';

PROMPT 47) ALL DETAILS OF EMPLOYEES HIRED BEFORE 1987;
select * from emp where hiredate < '01-jan-87';

PROMPT 48) ALL DETAILS WITH ANNUAL SALARY FOR EMPLOYEES WHOSE SALARY IS LESS THAN 5000;
select emp.*, sal*12 asal from emp where sal < 5000;

PROMPT 49) ALL DETAILS OF EMPLOYEES WHOSE JOB IS MANAGER;
select * from emp where job = 'manager';

PROMPT 50) ENAME, JOB AND DEPTNO OF EMPLOYEES WORKING IN DEPTNO 30;
select ename, job, deptno from emp where deptno = 30;

PROMPT 51) ALL DETAILS OF EMPLOYEES WHOSE JOB IS NOT SALESMAN;
select * from emp where job <> 'salesman';

PROMPT 52) ENAME AND JOB OF EMPLOYEES EXCEPT DEPTNO 20;
select ename, job from emp where deptno <> 20;

PROMPT 53) JOB, DEPTNO AND SAL OF EMPLOYEES EXCEPT SALESMAN;
select job, deptno, sal from emp where job <> 'salesman';

PROMPT 54) DESIGNATION (JOB) OF ALL EMPLOYEES EXCEPT KING;
select job designation from emp where ename <> 'king';

PROMPT 55) ALL DETAILS WITH 20% HIKE IN SALARY FOR EMPLOYEES HIRED AFTER 1985;
select emp.*, sal*1.20 hikesal from emp where hiredate > '31-dec-85';

PROMPT 56) ALL DETAILS WITH 12% DEDUCTION IN SALARY FOR EMPLOYEES HIRED BEFORE 1984;
select emp.*, sal*0.88 as dedusalary from emp where hiredate < '01-jan-84';

PROMPT 57) ALL DETAILS WITH 2000 BONUS FOR EMPLOYEE WHOSE EMPNO IS 7369;
select emp.*, sal+2000 as bonussalary from emp where empno = 7369;

PROMPT 58) ALL DETAILS OF EMPLOYEES NOT WORKING IN DEPTNO 10;
select * from emp where deptno <> 10;

PROMPT 59) ALL DETAILS WITH HALF TERM SALARY FOR EMPLOYEES WHOSE ANNUAL SALARY IS MORE THAN 14000;
select emp.*, (sal*12)/2 halfsalary from emp where sal*12 > 14000;

PROMPT 60) ALL DETAILS WITH 20% HIKE IN HALF TERM SALARY FOR EMPLOYEES WHOSE HALF TERM SALARY IS MORE THAN 7000;
select emp.*, (sal*12)/2*1.20 hikehalfsalary from emp where (sal*12)/2 > 7000;






-- >>>>>>>>>>> ASSIGNMENT ON LOGICAL OPERATOR >>>>>>>>>>
-- prompt 61) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING IN DEPTNO 10 AND 20?
select * from emp where deptno IN (10, 20);
-- prompt  ALL THE DETAILS OF THE EMPLOYEES  WHO ARE WORKING   AS MANAGER AND SALESMAN ;
select * from emp where job IN ('MANAGER' , 'SALESMAN');
-- prompt 63)  ALL THE DETAILS OF THE EMPLOYEES  WHOSE SAL IS MORE THEN 1000 AND LESS THEN 5000 ;
select * FROM emp where sal > 1000 and sal < 5000;
-- PROMPT 64) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE DEPTNO IS 20
   AND WORKING AS MANAGER ?
select * from emp where deptno = 20 and job = 'MANAGER';
-- PROMPT 65) WAQTD ALL THE EMPLOYEE NAME AND SALARY WHO HIRED AFTER 81
--      INTO DEPTNO 10 ?
SELECT  ENAME, SAL FROM EMP WHERE HIREDATE > '01-JAN-1982' and deptno = 10;
-- PROMPT WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE NAME IS 
--     KING AND SCOTT ?
select * from emp where ename = 'KING' OR ENAME = 'SCOTT';
-- 67) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SAL IS 
      -- 3000 AND 5000 ?
SELECT * from emp where sal = 3000 or sal = 5000;
-- 68) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHO ARE WORKING IN DEPTNO      
      -- 10 AS MANAGER AND HIRED ON ‘17-DEC-82 ?
select * from emp Where deptno = 10 and job = 'MANAGER' and hiredate = '17-DEC-1982';
-- 69) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING AS 
      -- PRESIDENT IN DEPTNO 10 AND HAVING SALARY OF 5000 ?
select * from emp where job = 'PRESIDENT' and deptno = 10 and sal = 5000;
-- 70) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WORKING IN DEPTNO 10,20
      -- AS MANAGER ?
select * from emp  where deptno in (10,20) and job = 'MANAGER';
-- 71) WAQTD ALL THE EMPLOYEES NAME AND JOB FOR  THE EMPLOYEES
--     WHO HIRED AFTER 81 AND BEFORE 87 ?
SELECT ename, job from emp where hiredate > '31-DEC-1981' and hiredate < '01-JAN-1987';
-- 72) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SALARY ARE MORE THEN   
--      1000 AND LESS THEN 5000 IN DEPTNO 20 ?
SELECT * FROM emp WHERE sal > 1000  AND sal < 5000 AND deptno = 20;
-- 73) WAQTD ALL THE DETAILS OF THE OF THE EMPLOYEES WHO ARE WORKING AS        
--      MANAGER IN DEPTNO 20 AND 10AND EARNING COMMISIONS 400,1600 ?
SELECT * FROM emp WHERE job = 'MANAGER' AND (deptno = 10 OR deptno = 20) AND (comm = 400 OR comm = 1600);

-- 74) WAQTD ENAME AND ANNAUL SALARY WITH ALISAS NAME FOR THE                  
--     E MPLOYEES WHOSE ANNUAL SALARY IS MORE THEN 800 IN DEPTNO 30 WORKING   AS SALESMAN AND HIRED BEFORE THE 88 ?
SELECT ename, sal*12 "asal" FROM emp WHERE sal*12 > 800 AND deptno = 30 AND job = 'SALESMAN' AND hiredate < '01-JAN-88';
-- 75) WAQTD ENAME AS A DEPTNO AS B AND JOB AS C FOR THE EMPLOYEES WHOSE COMM IS MORE THE 100 IN DEPTNO 10,20,30 ?
SELECT ename  A, deptno  B, job  C FROM emp WHERE comm > 100 AND (deptno = 10 OR deptno = 20 OR deptno = 30);
-- 76) WAQTD ALL THE DETAILS FOR THE EMPLOYEEES WHOSE HIREDATE ARE ‘03-DEC-81’ AND ‘17DEC-81’ INTO DEPTNO 30 ?
SELECT * FROM emp WHERE (hiredate = '03-DEC-81' OR hiredate = '17-DEC-81')
AND deptno = 30; 
-- 77) WAQTD JOB AND SALARY FOR THE EMPLOYEES WHOSE COMM IS LESS THEN 2000 AND SALARIES ARE MORE THEN 1000 IN DEPTNO 10, 20?
SELECT job, sal FROM emp WHERE comm < 2000 AND sal > 1000 AND (deptno = 10 OR deptno = 20);
-- 78) WAQTD ALL THE DEATILS  FOR THE EMPLOYEES WHOSE NAMES ARE KING AND SMITH AND ALLEN ?
SELECT * FROM emp WHERE ename = 'KING' OR ename = 'SMITH' OR ename = 'ALLEN';
-- 79) WAQTD ANNUAL SALARY HALF TERM SALARY WITH 25% DEDUCTION IN THE SALARY FOR THE EMPLOYEES WHOSE ANNUAL SALARY IS MORE THEN 6000 ?
select sal * 12 "ASAL" , ((sal * 6) *0.75) "HSAL25" from emp where sal* 12 > 6000;
-- 80) ALL THE DETAILS AND HALF TERM SALARY FOR SALESMAN AND MANAGER IN DEPTNO 10,30 ?
select emp.* , sal * 6 "hsal" from emp where (job ='SALESMAN' OR JOB = 'MANAGER') and deptno in(10,30);



-- >>>>>>>>>>> ASSIGNMENT ON SPECIAL OPERATOR >>>>>>>>>>>
-- >>>>>>>>>>> ASSIGNMENT ON SPECIAL OPERATOR >>>>>>>>>>>
-- 81) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING IN DEPTNO
--      10 AND 20?
select * from emp where deptno in(10, 20);
-- PROMPT 82) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHO ARE WORKING 
--     AS MANAGER AND SALESMAN ?
select * FROM emp where job in ('MANAGER','SALESMAN');
-- 83) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SAL IS MORE THEN 
--       1000 AND LESS THEN 5000 ?
    select * from emp where sal between 1000 and 5000;
-- 84) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE DEPTNO IS 20
--      AND WORKING AS MANAGER ?
select * from emp where deptno in (20) and job in ('MANAGER');
-- 85) WAQTD ALL THE EMPLOYEE NAME AND SALARY WHO HIRED AFTER 81
--       INTO DEPTNO 10 ?
SELECT ENAME, SAL FROM EMP WHERE HIREDATE > '31-DEC-81' AND DEPTNO IN (10);
-- 86) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE NAME IS 
--       KING AND SCOTT ?
select * from emp where ename in ('KING', 'SCOTT');
-- 87) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SAL IS 
--       3000 AND 5000 ?
SELECT * FROM emp WHERE sal IN (3000,5000);
-- 88) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHO ARE WORKING IN DEPTNO      
--       10 AS MANAGER AND HIRED ON ‘17-DEC-82 ?
select * FROM emp where deptno in (10) and job in ('MANAGER') and HIREDATE IN ('17-DEC-82');
-- 89) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING AS 
--       PRESIDENT IN DEPTNO 10 AND HAVING SALARY OF 5000 ?
select * from emp where job in ('president') and deptno in (10) and sal in (5000);
-- 90) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WORKING IN DEPTNO 10,20
--       AS MANAGER ?
select * from emp where deptno in (10,20) and job in ('manager');
-- 91) WAQTD ALL THE EMPLOYEES NAME AND JOB FRO THE EMPLOYEES
--     WHO HIRED AFTER 81 AND BEFORE 87 ?
select ename, job from emp where hiredate between  '31-dec-1981' and '01-jan-1987';
-- 92) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SALARY ARE MORE    THEN   1000 AND LESS THEN 5000 IN DEPTNO 20 ?
select * from emp where sal between 1000 and 5000 and deptno in (20);
-- 93) WAQTD ALL THE DETAILS OF THE OF THE EMPLOYEES WHO ARE WORKING AS        
--      MANAGER IN DEPTNO 20 AND 10AND EARNING COMMISIONS 400,1600 ?
select * from emp where job = 'MANAGER' and deptno in (10,20) and comm in (400,1600);
-- 94) WAQTD ENAME AND ANNAUL SALARY WITH ALISAS NAME FOR THE                    
--   E MPLOYEES WHOSE ANNUAL SALARY IS MORE THEN 800 IN DEPTNO 30 WORKING AS SALESMAN AND HIRED BEFORE THE 88 ?
select ename , sal * 12 ASAL from emp where sal*12 > 800 and deptno in (30) and job = 'SALESMAN' and hiredate < '01-JAN-1988';
-- 95) WAQTD ENAME AS A DEPTNO AS B AND JOB AS C FOR THE EMPLOYEES WHOSE COMM IS MORE THE 100 IN DEPTNO 10,20,30 ?
select ename A , deptno B, job C from emp where comm > 100 and deptno in (10,20,30);
-- 96) WAQTD ALL THE DETAILS FOR THE EMPLOYEEES WHOSE HIREDATE ARE ‘03-DEC-81’ AND ‘17DEC-81’ INTO DEPTNO 30 ?
select * from emp where hiredate in ('03-DEC-1981' , '17-DEC-1981') and deptno = 30;
-- 97) WAQTD JOB AND SALARY FOR THE EMPLOYEES WHOSE COMM IS LESS THEN 2000 AND SALARIES ARE MORE THEN 1000 IN DEPTNO 10, 20?
select job , sal from emp where comm < 2000 and sal > 1000 and deptno in (10,20);
-- 98) WAQTD ENAME FOR THE EMPLOYEES WHOSE NAMES ARE KING AND SMITH AND ALLEN ?
select ename from emp where ename in ('king','smith','allen');
-- 99) WAQTD ANNUAL SALARY HALF TERM SALARY WITH 25% DEDUCTION IN THE SALARY FOR THE EMPLOYEES WHOSE ANNUAL SALARY IS MORE THEN 6000 ?
select sal*12 as annual_sal, (sal*6) - (sal*6*0.25) as halfsal from emp where sal*12 > 6000;

-- 100) ALL THE DETAILS AND HALF TERM SALARY FOR SALESMAN AND MANAGER IN DEPTNO 10,30 ?
select emp.*, sal*6 as halfsal from emp where job in ('salesman','manager') and deptno in (10,30);
-- 101) ) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHOSE HIRED BETWEEN 81 TO 89  INTO DEPTNO 20 ?
select * from emp where hiredate between '01-jan-81' and '31-dec-89' and deptno in (20);
-- 102) WAQTD DETAILS FOR THE EMPLOYEES WHOSE SALARY IN THE RANGE OF 1000 TO 5000 IN DEPTNO 10,20 ?
select * from emp where sal between 1000 and 5000 and deptno in (10,20);
-- 103) WAQTD ENAME AND JOB FOR THE EMPLOYEES WHO ARE WORKING AS ANAGER AND EARNING COMMISION IN THE RANGE OF 100 TO 1000 ?
select ename, job from emp where job in ('manager') and comm between 100 and 1000;
-- 104) WAQTD ALL THE DEATILS ALONG WITH 3 MONTHS SALARY FOR THE EMPLOYEES WHOSE SALARY IS NOT NULL AND DOESNT HAVING ANY REPORTING 
-- MANAGER  ?
select emp.*, sal*3 as three_month_sal from emp where sal is not null and mgr is null;
-- 105) WAQTD ENAME AND SALARY AND JIB FOR THE EMPLOYEES WORKING AS SALESMAN IN DEPTNO 30 AND EARNING SALARY BUT NOT COMMISION AND HIRED BETWEEN 82  TO 88 ? 
select ename, sal, job from emp where job in ('salesman') and deptno in (30) and comm is null and hiredate between '01-jan-82' and '31-dec-88';
-- 106) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHO ARE EARNING SALARY ?
select * from emp where sal is not null;
-- 107) WAQTD ANNAUL SALARY OF THE EMPLOYEE WHO ARE NOT EARNING COMMISSION ?
select sal*12  asal from emp where comm is null;
-- 108) WAQTD ALL THE DETAILS WITH ANNAUL COMMISSION FOR THE EMPLOYEE WHO  ARE WORKING IN DEPT 10 AND DONT HAVE ANY REPORTING MANAGER ?
select emp.*, comm*12  acomm from emp where deptno in (10) and mgr is null;
-- 109) WAQTD ALL THE DETAILS OF THE EMPLOYEE EXCEPT DEPTNO 10 AND WHO WHO HAVE REPORTING MAMAGER ?
select * from emp where deptno not in (10) and mgr is not null;
-- 110) WAQTD ENAME AND SALARY. AND COMMISSION OF THE EMPLOYEE WHO EARNING COMMISSION IN DEPT NO 30 AND WORKING AS SALESMAN ?
select ename, sal, comm from emp where comm is not null and deptno in (30) and job in ('salesman');
-- 111) WAQTD ENAME OF THE EMPLOYEE WHOSE NAME START WITH S ?
select ename from emp where   regexp_like (ename, '^S');

-- 112 ) WAQTD ALL THE DETAILS FOR THE EMPLOYEE WHOSE NAME 
-- ENDS WITH R ?
select * from emp where  regexp_like (ename, 'R$');
-- 113 ) WAQTD SALARY AND DEEPTNO AND NAME FOR THE EMPLOYEE 
-- WHOSE NAME HAVING A CHARACTER ?
select sal , deptno, ename from emp where regexp_like(ename, '.*a.*');
-- 114 ) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE HAVING 
-- 2 A IN THEIR NAME ?
select * FROM emp where regexp_like(ename, 'a.*a');
-- 115 ) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME HAVING 
-- CONJUGATIVE A IN THEIR NAMES ?
select * from emp where regexp_like(ename, 'aa');
-- 116) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME HAVING 
-- 2ND CHARACTER AS M ?
select * from emp where regexp_like(ename, '^.m');
-- 117) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME HAVING LAST 2ND CHAPTER AS E ?
select * from emp where regexp_like(ename, 'e.$');
-- 118) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME START WITH 
-- M HAVING 4TH CHARACTER L AND ENDS WITH R ?
select * from emp where regexp_like(ename, '^m..l.*r$');
-- 119) WAQTD ALL THE DETAILS OF AN ALL THE EMPLOYEE WHO ARE 
-- EARNING 4 DOGIT OF SALARY AND NAMES STARTS WITH VOWELS ?
select * from emp where regexp_like(ename, '^[aeiou]') and regexp_like(sal, '^[0-9]{4}$');
-- 120 ) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME 
-- STARTS WITH CONSONANTS. ?
select * from emp where regexp_like(ename, '^[^aeiou]');
-- 121) WAQTD ENAME AND HIREDATE OF ALL THE EMPLOYEE WHO
-- HIRED IN THE MONTH OF DEC ?
select ename, hiredate from emp where  regexp_like(hiredate,'dec');
-- 122) WAQTD ALL THE DETAILS FOR THE EMPLOYEE WHO HIRED 
-- DURING 1981 ?
-- 123) WAQTD ALL THE DETAILS OF THE EMPLOYEE EXCEPT 
-- WHOSE NAME HAVING A ?
select * from emp where not regexp_like(ename,'a');
-- 124) WAQTD SALARY AND NAMES FOR THE EMPLOYEE WHOSE
-- NAME START WITH S EXCEPT THE EMPLOYEE
-- WHOSE SALARY. STARTS WITH 1 ?
select ename, sal from emp where regexp_like(ename,'^s') and not regexp_like(sal,'^1');
-- 125) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE 
-- NAME HAVING 2 TIME CONSUGATIVE. A ?
select * from emp where regexp_like(ename,'aa');
-- 126) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME START 
-- WITH % ?
select * from emp where ename like '@%%' escape '@';
-- 127) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME ENDS 
-- WITH % ?
select * from emp where ename like '%1%'escape '1';
-- 128) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME START 
-- WITH % ENDS WITH _ ?
select * from emp where ename like '1%%1_' escape '1';
-- 129) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME HAVING % ?
select * from emp where ename like '1%%' escape '1';
-- 130) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME START 
-- WITH % HAVING 4TH CHARACTER _ AND ENDS WITH % ?

select * from emp where regexp_like(ename,'^%.._.*%$');










-- >>>>>>>>>>>>>>ASSINGMENT ON MRF >>>>>>>>>>>>>>>>>>

--- 131) WAQTD MAX SALARY FROM THE EMPLOYEE TABLE ?
select max(sal) from emp;
-- 132) WAQTD MAX AND MIN COMM FROM EMPLOYEES TABLE ?
select max(comm) , min(comm) from emp;
-- 133) WAQTD TOTAL SALARY NEEDED TO PAY FOR THE SALESMAN ?
select sum(sal) totalsalary from emp where job = 'SALESMAN';
-- 134) WAQTD NUMBER OF EMPLOYEES WORKING IN DEPTNO 30 ?
select count(ename) from emp where deptno =30;
-- 135) WAQTD NUMBER OF EMPLOYEES WORKING AS MANAGER IN DEPTNO 20?
select count(ename) from emp where job = 'MANAGER' and deptno =20;
-- 136) WAQTD MAX SALARY NEEDED TO PAY FOR THE EMPLOYEES WHOSE NAME STARTS WITH A ?
select max(sal) from emp where ename like 'A%';
-- 137) WAQTD AVG SALARY NEEDED TO PAY FOR THE EMPLOYEES OF DEPTNO 10 ?
select avg(sal) from emp where deptno =10;
-- 138) WAQTD TOTAL SALARY AND AVG SALARY NEEDED TO PAY FOR THE EMPLOYEES WHO ARE HIRED IN THE RANGE OF 81 TO 87 ?
select sum(sal), avg(sal) from emp where hiredate BETWEEN '01-JAN-1981' and '31-DEC-1987';
-- 139) WAQTD NUMBER OF EMPLOYEES WORKING IN DEPTNO 40 ?
select count(ename) from emp where deptno in (40);
-- 140) WAQTD TOTAL SALARY NEEDED TO PAY FOR THE EMPLOYEES WHO ARE REPORTING TO 7839 ?
select sum(sal) from emp where mgr = 7839;
-- 141) WAQTD HOW MANY EMPLOYEES ARE WORKIN AS PRESIDENT IN DEPTNO 10 AND EARNING SALARY MORE THEN 4000 ?
select count(ename) from emp where job = 'PRESIDENT' AND deptno in (10) and sal > 4000;
-- 142) WAQTD HOW MANY EMPLOYEES ARE WORKIN AS SALESMAN IN DEPTNO 30 AND EARNING SALARY LESS THEN 5000 ?
select count(ename) from emp where job = 'SALESMAN' AND deptno in (30) and sal < 5000;

-- 143) WAQTD HOW MANAY EMPLOYEES ARE HIRED ON 03-DEC- 81 iN DEPTNO 10 , 20
select count(ename) from emp where hiredate ='03-DEC-1981' and deptno in (10 ,20);
-- 144) WAQTD HOW MUCH TOTAL SALARY NEEDE TO PAY FOR THE EMPLOYEE
-- WHOSE MAME HAVING A CHARACTER ?
select sum(sal) from emp where ename like '%A%';

-- 145) WAQTD AVG SALARY NEEDED TO PAY FOR THE SALESMAN IN DEPTNO 30 ?
select avg(sal) from emp where job = 'SALESMAN' and deptno = 30;





-- >>>>>>>>> ASSIGNMENT ON GROUP BY CLAUSE >>>>>>>>>>>>>


-- 146).WAQTD NUMBER OF EMPLOYEES WORKING IN EACH DEPARTEMENT EXCEPT PRESIDENT. ?
select count(ename), deptno from emp where job <> 'PRESIDENT' GROUP BY deptno;
-- 147)WAQTD TOTAL SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH JOB. ?
select sum(sal) , job from emp GROUP BY job;
-- 148)WAQTD NUMBER OF EMPLOYEEES WORKING AS MANAGER IN EACH DEPARTMENT. ?
select count(ename), deptno departmentno from emp where job = 'MANAGER' GROUP BY deptno;
-- 149).WAQTD AVG SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH DEPARTMENT EXCLUDING THE EMPLOYEES OF DEPTNO 20 . ? 
select avg(sal) , deptno from emp where deptno <> 20 group  by deptno;
-- 150).WAQTD NUMBER OF EMPLOYEES HAVING CHARACTER 'A' IN THEIR NAMES IN EACH JOB.  ?
select count(ename) , job from emp where ename like '%A%' GROUP BY job;
-- 151).WAQTD NUMBER OF EMPLOYEES AND AVG SALARY NEEDED TO PAY THE EMPLOYEES WHO SALARY IN GREATER THAN 2000 IN EACH DEPT. ?
select count(ename), avg(sal) , deptno from emp where sal > 2000 group BY deptno;
-- 152)WAQT D TOTAL SALARY NEEDED TO PAY AND NUMBER OF SALESMANS IN EACH DEPT. ?
select sum(sal) ,count(ename), deptno from emp where job = 'SALESMAN' GROUP BY deptno;
-- 153)WAQTD NUMBER OF EMPLOYEES WITH THEIR MAXIMUM SALARIES IN EACH JOB. ?
select count(ename) , max(sal) , job from emp GROUP BY job;
-- 154) WAQTD MAXIMUM SALARIES GIVEN TO AN EMPLOYEE 
-- WORKING IN EACH DEPT. ?
select max(sal) , deptno from emp GROUP BY deptno;
-- 155)WAQTD NUMBER OF TIMES THE SALARIES PRESENT IN EMPLOYEE TABLE. ?
select count(sal) , sal from emp GROUP BY sal;


-- <<<<<<<<<<<ASSIGNMENT QUESTIONS ON HAVING CLAUSE>>>>>>>>>>>>

-- 156).WAQTD DNO AND NUMBER OF EMP WORKING IN EACH DEPT IF THERE ARE ATLEAST 2 CLERKS IN EACH DEPT ?
select count(*), deptno 
from emp
where job = 'CLERK'
group by deptno
having count(*) >=2;


-- 157)WAQTD DNO AND TOTAL SAALARY NEEDED TO PAY ALL EMP IN EACH DEPT IF THERE ARE ATLEAST 4 EMP IN EACH DEPT ?
SELECT DEPTNO , SUM(SAL)
FROM EMP
GROUP BY DEPTNO
HAVING COUNT(*) >= 4;


-- 158).WAQTD NUMBER OF EMP EARNING SAL MORE THAN 1200 IN EACH JOB AND THE TOTAL SAL NEEDED TO PAY EMP OF EACH JOB MUST EXCEEDS 3800 ?
SELECT COUNT(*), JOB
FROM EMP
WHERE SAL > 1200
GROUP BY JOB
HAVING SUM(SAL) > 3800 ;

-- 159).WAQTD DEPTNO AND NUMBER OF EMP WORKING ONLY IF THERE ARE 2 EMP WORKING IN EACH DEPT AS MANAGER. ?
SELECT DEPTNO, COUNT(*)
FROM EMP
WHERE JOB = 'MANAGER'
GROUP BY DEPTNO
HAVING COUNT(*) = 2;

-- 160) WAQTD JOB AND MAX SAL OF EMP IN EACH JOB IF THE MAX SAL EXCEEDS 2600 ?
SELECT JOB, MAX(SAL)
FROM EMP
GROUP BY JOB
HAVING MAX(SAL) > 2600;

-- 161). WAQTD THE SALARIES WHICH ARE REPEATED IN EMP TABLE ?
SELECT SAL
FROM EMP
GROUP BY SAL
HAVING COUNT(*) > 1;

-- 162).WAQTD THE HIREDATE WHICH ARE DUPLICATED IN EMP TABLE ?
SELECT HIREDATE
FROM EMP
GROUP BY HIREDATE
HAVING COUNT(*) > 1;

-- 164) WAQTD AVG SALARY OF EACH DEPT IF AVG SAL IS LESS THAN 3000 ?
SELECT AVG(SAL), DEPTNO
FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL) < 3000;

-- 164) WAQTD DEPTNO IF THERE ARE ATLEAST 3 EMP IN EACH DEPT WHOS NAME HAS CHAR 'A' OR 'S' ?
SELECT DEPTNO
FROM EMP
WHERE ENAME LIKE '%A%' OR ENAME LIKE '%S%'
GROUP BY DEPTNO
HAVING COUNT(*) >=3;

-- 165).WAQTD MIN AND MAX SALARIES OF EACH JOB IF MIN SAL IS MORE THAN 1000 AND MAX SAL IS LESS THAN 5000.
SELECT MIN(SAL) , MAX(SAL), JOB
FROM EMP
GROUP BY JOB
HAVING MIN(SAL) > 1000 AND MAX(SAL) < 5000;






-- <<<<<<<<<ASSIGNMENT ON SUB QUERIES>>>> >>>>
-- ASSIGNMENT ON CASE 1



-- 166).WAQTD NAME OF THE EMPLOYEES EARNING MORE THAN ADAMS ?
SELECT ENAME
FROM EMP
WHERE SAL >(SELECT SAL FROM EMP WHERE ENAME = 'ADAMS');

-- 167).WAQTD NAME AND SALARY OF THE EMPLOYEES EARNING LESS THAN KING
SELECT ENAME, SAL FROM EMP
WHERE SAL < (SELECT SAL FROM EMP WHERE ENAME='KING');

-- 168) WAQTD NAME AND DEPTNO OF THE EMPLOYEES IF THEY ARE WORKING IN THE SAME DEPT AS JONES
SELECT ENAME, DEPTNO FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME='JONES');

-- 169) WAQTD NAME AND JOB OF ALL THE EMPLOYEES WORKING IN THE SAME DESIGNATION AS JAMES 
SELECT ENAME, JOB FROM EMP
WHERE JOB IN (SELECT JOB FROM EMP WHERE ENAME='JAMES');

-- 170)WAQTD EMPNO AND ENAME ALONG WITH ANNUAL SALARY OF ALL THE EMPLOYEES IF THEIR ANNUAL SALARY IS
-- GREATER THAN WARDS ANNUAL SALARY.
SELECT EMPNO,ENAME, SAL*12 ASAL FROM EMP 
WHERE SAL*12 > (SELECT SAL*12 FROM EMP WHERE ENAME='WARD');
-- 171) .WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY
-- ARE HIRED BEFORE SCOTT AND HIRED AFTER THE PRESIDENT ?
SELECT ENAME, HIREDATE FROM EMP 
WHERE HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME='SCOTT' ) AND HIREDATE > (SELECT HIREDATE FROM EMP WHERE JOB='PRESIDENT' );

-- 172) .WAQTD NAME AND SAL OF THE EMPLOYEE IF THEY ARE EARNING SAL LESS THAN THE EMPLOYEE WHOS EMPNO IS 7839
SELECT ENAME, SAL FROM EMP WHERE  SAL < (SELECT SAL FROM EMP WHERE EMPNO=7839);

-- 173).WAQTD ALL THE DETAILS OF THE EMPLOYEES IF THE EMPLOYEES ARE HIRED BEFORE MILLER 
SELECT * FROM EMP WHERE HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME='MILLER');

-- 174) .WAQTD ENAME AND EMPNO OF THE EMPLOYEES IF EMPLOYEES ARE EARNING MORE THAN ALLEN
SELECT ENAME, EMPNO FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME='ALLEN');

-- 175).WAQTD ENAME AND SALARY OF ALL THE EMPLOYEES WHO ARE EARNING MORE THAN MILLER BUT LESS THAN ALLEN.
SELECT ENAME,SAL FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME='MILLER') AND  SAL < (SELECT SAL FROM EMP WHERE ENAME='ALLEN');

-- 178).WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING IN DEPT 20 AND WORKING IN THE SAME DESIGNATION AS SMITH 
SELECT * FROM EMP WHERE DEPTNO = 20 AND JOB =(SELECT JOB FROM EMP WHERE  ENAME='SMITH');

-- 179).WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE SAME DEPT AS TURNER
SELECT * FROM EMP WHERE JOB='MANAGER'AND DEPTNO =(SELECT DEPTNO FROM EMP WHERE ENAME='TURNER');

-- 180).WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED AFTER 1980 AND BEFORE KING 
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE > '31-DEC-1980' AND HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME='KING');

-- 181).WAQTD ALL THE DETAILS OF EMPLOYEES WHO EARN MORE THAN SCOTT BUT LESS THAN KING
SELECT * FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME='SCOTT') AND  SAL < (SELECT SAL FROM EMP WHERE ENAME='KING');


-- 182).WAQTD NAME OF THE EMPLOYEES WHOS NAME STARTS WITH 'A' AND WORKS IN THE SAME DEPT AS BLAKE 
SELECT ENAME FROM EMP WHERE ENAME LIKE 'A%' AND DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME='BLAKE');

-- 183).WAQTD NAME AND COMM IF EMPLOYEES EARN COMMISSION
-- AND WORK IN THE SAME DESIGNATION AS SMITH
SELECT ENAME, COMM FROM EMP WHERE COMM > 0 AND JOB=(SELECT MAX(JOB) FROM EMP WHERE ENAME='SMITH');

-- 184).WAQTD DETAILS OF ALL THE EMPLOYEES WORKING AS CLERK IN THE SAME DEPT AS TURNER.
SELECT * FROM EMP WHERE JOB='CLERK' AND DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME='TURNER');

-- 185).WAQTD ENAME, SAL AND DESIGNATION OF THE EMPLOYEES WHOS ANNUAL SALARY IS MORE THAN SMITH AND LESS THAN KING.
SELECT ENAME,SAL ,JOB FROM EMP WHERE SAL*12 > (SELECT MAX(SAL*12) FROM EMP WHERE ENAME='SMITH' ) AND SAL*12 < (SELECT MIN(SAL*12) FROM EMP WHERE ENAME='KING');









-- ASSIGNMENT ON CASE 2:

-- 186).WAQTD DNAME OF THE EMPLOYEES WHOS NAME IS SMITH 
SELECT DNAME FROM DEPT WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME='SMITH');

-- 187).WAQTD DNAME AND LOC OF THE EMPLOYEE WHOS
-- ENAME IS KING 
SELECT DNAME, LOC FROM DEPT WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE  ENAME='KING');

-- 188).WAQTD LOC OF THE EMP WHOS EMPLOYEE NUMBER IS
-- 7902
SELECT LOC FROM DEPT WHERE DEPTNO =(SELECT DEPTNO FROM EMP WHERE EMPNO = 7902);

--  189) WAQTD DNAME AND LOC ALONG WITH DEPTNO OF THE EMPLOYEE WHOS NAME ENDS WITH 'R'.
SELECT DNAME, LOC ,DEPTNO FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME LIKE '%R');

-- 190) .WAQTD DNAME OF THE EMPLOYEE WHOS DESIGNATION IS PRESIDENT
SELECT DNAME FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE JOB='PRESIDENT');

-- 191) .WAQTD NAMES OF THE EMPLOYEES WORKING IN
-- ACCOUNTING DEPARTMENT
SELECT ENAME FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME='ACCOUNTING');

--  192) .WAQTD ENAME AND SALARIES OF THE EMPLOYEES WHO ARE WORKING IN THE LOCATION CHICAGO
SELECT ENAME, SAL FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC='CHICAGO');

-- 193). WAQTD DETAILS OF THE EMPLOYEES WORKING IN SALES 
SELECT * FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME='SALES');

-- 194) .WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL
-- SALARY IF EMPLOYEES ARE WORKING IN NEW YORK
SELECT EMP.*, SAL*12 ASAL FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK');

--  195) .WAQTD NAMES OF EMPLOYEES WORKING IN OPERATIONS DEPARTMENT
SELECT  ENAME FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME='OPERATIONS');


-- ASSIGNMENT ON CASE 1 & 2

--- 195) .WAQTD NAMES OF THE EMPLOYEES EARNING MORE THAN SCOTT IN ACCOUNTING DEPT
SELECT ENAME FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME='ACCOUNTING'  ) AND SAL > (SELECT SAL FROM EMP WHERE ENAME='SCOTT');
-- 196). WAQTD DETAILS OF THE EMPLOYEES WORKING AS
-- MANAGER IN THE LOCATION CHICAGO 
SELECT * FROM EMP WHERE JOB='MANAGER' AND DEPTNO IN(SELECT DEPTNO FROM DEPT WHERE LOC='CHICAGO');
-- 197) .WAQTD NAME AND SAL OF THE EMPLOYEES EARNING MORE THAN KING IN THE DEPT ACCOUNTING
SELECT ENAME, SAL FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME='ACCOUNTING' )AND SAL > (SELECT SAL FROM EMP WHERE ENAME ='KING');
-- 198) .WAQTD DETAILS OF THE EMPLOYEES WORKING AS
-- SALESMAN IN THE DEPARTEMENT SALES 
SELECT * FROM EMP WHERE JOB='SALESMAN' AND DEPTNO IN(SELECT DEPTNO FROM DEPT WHERE DNAME='SALES');
-- 199) .WAQTD NAME, SAL. JOB, HIREDATE OF THE EMPLOYEES WORKING IN OPERATIONS DEPARTMENT AND HIRED BEFORE KING
SELECT ENAME, SAL, JOB, HIREDATE FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME='OPERATIONS') AND HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME='KING');
-- 200) .DISPLAY ALL THE EMPLOYEES WHOSE DEPARTMET NAMES ENDING 'S'.
SELECT * FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME LIKE '%S');
-- 201) .WAQTD DNAME OF THE EMPLOYEES WHOS NAMES HAS CHARACTER 'A' IN IT.
SELECT DNAME FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE  ENAME LIKE '%A%') ;
-- 202) . WAQTD DNAME AND LOC OF THE EMPLOYEES WHOS
-- SALARY IS RUPEES 800. 
SELECT DNAME , LOC FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE SAL = 800);
-- 203) .WAQTD DNAME OF THE EMPLOYEES WHO EARN COMISSION
SELECT DNAME FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE COMM > 0);
-- 204) .WAQTD LOC OF THE EMPLOYEES IF THEY EARN COMISSION IN DEPT 40 
SELECT LOC FROM DEPT WHERE DEPTNO = 40 AND DEPTNO IN (SELECT DEPTNO FROM EMP WHERE COMM > 0); 



-- ASSIGNMENT ON TYPES OF SUB QUERY.

-- 205) .WAQTD NAME OF THE EMPLOYEES EARNING SALARY MORE THAN THE SALESMAN
SELECT ENAME FROM EMP
WHERE SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB='SALESMAN');
-- 206) WAQTD DETAILS OF THE EMPLOYEES HIRED AFTER ALL THE CLERKS
SELECT * FROM EMP
WHERE HIREDATE > (SELECT MAX(HIREDATE) FROM EMP WHERE JOB='CLERK' );

--  208) WAQTD NAME AND HIREDATE OF EMPLOYEES HIRED BEFORE ALL THE MANAGERS
SELECT ENAME, HIREDATE FROM EMP
WHERE HIREDATE < (SELECT MIN(HIREDATE) FROM EMP WHERE JOB='MANAGER');

-- 209) .WAQTD NAMES OF THE EMPLOYEES HIRED AFTER ALL THE MANAGERS AND EARNING SALARY MORE THAN ALL THE CLERKS
SELECT ENAME FROM EMP
WHERE HIREDATE > (SELECT MAX(HIREDATE) FROM EMP WHERE JOB='MANAGER') AND SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB='CLERK');

-- 210) .WAQTD DETAILS OF THE EMPLOYEES WORKING AS CLERK AND HIRED BEFORE ATLEST A SALESMAN 
SELECT * FROM EMP 
WHERE JOB='CLERK' AND HIREDATE < (SELECT MAX(HIREDATE) FROM EMP WHERE JOB='SALESMAN');

--  211).WAQTD DETAILS OF EMPLOYEES WORKING IN ACCOUNTING OR SALES DEPT
SELECT * FROM EMP 
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME='ACCOUNTING' OR DNAME='SALES' );
-- 212) WAQTD DEPARTMENT NAMES OF THE EMPOYEES WITH NAME SMITH, KING AND MILLER
SELECT DNAME FROM DEPT 
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME='SMITH' OR ENAME='KING' OR ENAME='MILLER');

-- 213) .WAQTD DETAILS OF EMPLOYEES WORKING NEWYORK OR CHICAGO
SELECT * FROM EMP 
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK' OR LOC='CHICAGO');

-- 214)  WAQTD EMP NAMES IF EMPLOYEES ARE HIRED AFTER ALL THE EMPLOYEES OF DEPT 10
SELECT ENAME FROM EMP
WHERE HIREDATE > (SELECT MAX(HIREDATE) FROM EMP WHERE DEPTNO=10);





-- 166) WAQTD NAME OF THE EMPLOYEES EARNING MORE THAN ADAMS
SELECT ENAME 
FROM EMP 
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME='ADAMS');

-- 167) WAQTD NAME AND SALARY OF THE EMPLOYEES EARNING LESS THAN KING
SELECT ENAME, SAL 
FROM EMP 
WHERE SAL < (SELECT SAL FROM EMP WHERE ENAME='KING');

-- 168) WAQTD NAME AND DEPTNO OF THE EMPLOYEES IF THEY ARE WORKING IN THE SAME DEPT AS JONES
SELECT ENAME, DEPTNO 
FROM EMP 
WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME='JONES');

-- 169) WAQTD NAME AND JOB OF ALL THE EMPLOYEES WORKING IN THE SAME DESIGNATION AS JAMES
SELECT ENAME, JOB 
FROM EMP 
WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME='JAMES');

-- 170) WAQTD EMPNO AND ENAME ALONG WITH ANNUAL SALARY OF EMPLOYEES IF THEIR ANNUAL SALARY IS GREATER THAN WARD
SELECT EMPNO, ENAME, SAL*12 AS ANNUAL_SAL 
FROM EMP 
WHERE SAL*12 > (SELECT SAL*12 FROM EMP WHERE ENAME='WARD');

-- 171) WAQTD NAME AND HIREDATE OF EMPLOYEES HIRED BEFORE SCOTT AND AFTER PRESIDENT
SELECT ENAME, HIREDATE 
FROM EMP 
WHERE HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME='SCOTT')
AND HIREDATE > (SELECT HIREDATE FROM EMP WHERE JOB='PRESIDENT');

-- 172) WAQTD NAME AND SAL OF EMPLOYEE EARNING LESS THAN EMPNO 7839
SELECT ENAME, SAL 
FROM EMP 
WHERE SAL < (SELECT SAL FROM EMP WHERE EMPNO=7839);

-- 173) WAQTD ALL DETAILS OF EMPLOYEES HIRED BEFORE MILLER
SELECT * 
FROM EMP 
WHERE HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME='MILLER');

-- 174) WAQTD ENAME AND EMPNO OF EMPLOYEES EARNING MORE THAN ALLEN
SELECT ENAME, EMPNO 
FROM EMP 
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME='ALLEN');


-- 175) WAQTD ENAME AND SALARY OF EMPLOYEES EARNING MORE THAN MILLER BUT LESS THAN ALLEN
SELECT ENAME, SAL 
FROM EMP 
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME='MILLER')
AND SAL < (SELECT SAL FROM EMP WHERE ENAME='ALLEN');

-- 176) WAQTD ALL DETAILS OF EMPLOYEES IN DEPT 20 AND SAME DESIGNATION AS SMITH
SELECT * 
FROM EMP 
WHERE DEPTNO=20 
AND JOB = (SELECT JOB FROM EMP WHERE ENAME='SMITH');

-- 177) WAQTD ALL DETAILS OF EMPLOYEES WORKING AS MANAGER IN SAME DEPT AS TURNER
SELECT * 
FROM EMP 
WHERE JOB='MANAGER' 
AND DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME='TURNER');


-- 178) WAQTD NAME AND HIREDATE OF EMPLOYEES HIRED AFTER 1980 AND BEFORE KING
SELECT ENAME, HIREDATE 
FROM EMP 
WHERE HIREDATE > '31-DEC-1980'
AND HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME='KING');

-- 179) WAQTD ALL DETAILS OF EMPLOYEES WHO EARN MORE THAN SCOTT BUT LESS THAN KING
SELECT * 
FROM EMP 
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME='SCOTT')
AND SAL < (SELECT SAL FROM EMP WHERE ENAME='KING');


-- 180) WAQTD NAME OF EMPLOYEES WHOSE NAME STARTS WITH 'A' AND SAME DEPT AS BLAKE
SELECT ENAME 
FROM EMP 
WHERE ENAME LIKE 'A%' 
AND DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME='BLAKE');

-- 181) WAQTD NAME AND COMM OF EMPLOYEES WHO EARN COMMISSION AND SAME DESIGNATION AS SMITH
SELECT ENAME, COMM 
FROM EMP 
WHERE COMM IS NOT NULL 
AND JOB = (SELECT JOB FROM EMP WHERE ENAME='SMITH');


-- 182) WAQTD DETAILS OF EMPLOYEES WORKING AS CLERK IN SAME DEPT AS TURNER
SELECT * 
FROM EMP 
WHERE JOB='CLERK' 
AND DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME='TURNER');

-- 183) WAQTD ENAME, SAL AND JOB OF EMPLOYEES WHOSE ANNUAL SALARY IS MORE THAN SMITH AND LESS THAN KING
SELECT ENAME, SAL, JOB 
FROM EMP 
WHERE SAL*12 > (SELECT SAL*12 FROM EMP WHERE ENAME='SMITH')
AND SAL*12 < (SELECT SAL*12 FROM EMP WHERE ENAME='KING');




-- WAQTD DNAME OF THE EMPLOYEES WHOS NAME IS SMITH 
SELECT DNAME 
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME='SMITH');
-- WAQTD DNAME AND LOC OF THE EMPLOYEE WHOS ENAME IS KING 
SELECT DNAME , LOC
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME='KING');
-- WAQTD LOC OF THE EMP WHOS EMPLOYEE NUMBER IS 7902
SELECT LOC 
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE EMPNO=7902);

-- WAQTD DNAME AND LOC ALONG WITH DEPTNO OF THE EMPLOYEE WHOS NAME ENDS WITH 'R'.
SELECT DNAME , LOC, DEPTNO
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME LIKE '%R');
-- WAQTD DNAME OF THE EMPLOYEE WHOS DESIGNATION IS PRESIDENT
SELECT DNAME 
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE JOB='PRESIDENT');
-- WAQTD NAMES OF THE EMPLOYEES WORKING IN ACCOUNTING DEPARTMENT
SELECT ENAME 
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME='ACCOUNTING');
-- WAQTD DNAME OF THE EMPLOYEE WHOS DESIGNATION IS PRESIDENT
SELECT DNAME 
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE JOB='PRESIDENT');
-- WAQTD DNAME OF THE EMPLOYEE WHOS DESIGNATION IS PRESIDENT
SELECT DNAME 
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE JOB='PRESIDENT');

-- WAQTD ENAME AND SALARIES OF THE EMPLOYEES WHO ARE WORKING IN THE LOCATION CHICAGO
SELECT ENAME ,SAL
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC='CHICAGO');
-- WAQTD DETAILS OF THE EMPLOYEES WORKING IN SALES 
SELECT *
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME='SALES');
-- WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL SALARY IF EMPLOYEES ARE WORKING IN NEW YORK
SELECT EMP.* ,SAL*12 ASAL
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK');
-- WAQTD NAMES OF EMPLOYEES WORKING IN OPERATIONS DEPARTMENT
SELECT ENAME 
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME='OPERATIONS');




-- WAQTD NAMES OF THE EMPLOYEES EARNING MORE THAN SCOTT IN ACCOUNTING DEPT
SELECT ENAME 
FROM EMP
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME='SCOTT') AND
      DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME='ACCOUNTING');
-- WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE LOCATION CHICAGO 
SELECT * 
FROM EMP S
WHERE JOB='MANAGER' AND
        DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC='CHICAGO');
-- WAQTD NAME AND SAL OF THE EMPLOYEES EARNING MORE THAN KING IN THE DEPT ACCOUNTING
SELECT ENAME ,SAL
FROM EMP
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME='KING') AND
        DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME='ACCOUNTING');

-- WAQTD DETAILS OF THE EMPLOYEES WORKING AS SALESMAN IN THE DEPARTEMENT SALES 
SELECT * 
FROM EMP 
WHERE JOB='SALESMAN' AND
        DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME='SALES');

-- WAQTD NAME, SAL. JOB, HIREDATE OF THE EMPLOYEES WORKING IN OPERATIONS DEPARTMENT AND HIRED BEFORE KING
SELECT ENAME, SAL, JOB, HIREDATE
FROM EMP   
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME='OPERATIONS') AND
    HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME='KING');
-- DISPLAY ALL THE EMPLOYEES WHOSE DEPARTMET NAMES ENDING 'S'.
SELECT * 
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME LIKE '%S');
-- WAQTD DNAME OF THE EMPLOYEES WHOS NAMES HAS CHARACTER 'A' IN IT.
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME LIKE '%A%');
-- WAQTD DNAME AND LOC OF THE EMPLOYEES WHOS SALARY IS RUPEES 800. 
SELECT DNAME , LOC
FROM DEPT
WHERE DEPTNO IN(SELECT DEPTNO FROM EMP WHERE SAL=800);
-- WAQTD DNAME OF THE EMPLOYEES WHO EARN COMISSION
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE COMM IS NOT NULL);
-- WAQTD LOC OF THE EMPLOYEES IF THEY EARN COMISSION IN DEPT 40
SELECT LOC
FROM DEPT
WHERE DEPTNO IN(SELECT DEPTNO FROM EMP WHERE COMM IS NOT NULL ) AND
        DEPTNO=40;



-- ASSIGNMENT ON NESTED SUB QUERY:

--- 61. WAQTD 2ND MINIMUM SALARY
SELECT MAX(SAL) SECMAX
FROM EMP WHERE SAL <(SELECT MAX(SAL) FROM EMP);

-- 62. WAQTD 5TH MAXIMUM SALARY
SELECT MAX(SAL) FIFTHMAX
FROM EMP
WHERE SAL =
        (SELECT MAX(SAL) FROM EMP
WHERE SAL <
        (SELECT MAX(SAL) FROM EMP
WHERE SAL < 
        (SELECT MAX(SAL) FROM EMP
WHERE SAL < 
        (SELECT MAX(SAL) FROM EMP
WHERE SAL < 
        (SELECT MAX(SAL) FROM EMP        
)))));
        


-- 63. WAQTD NAME OF THE EMPLOYEE EARNING 3RD MAXIMUM SALARY
SELECT ENAME
FROM EMP
WHERE SAL = (SELECT MAX(SAL) FROM EMP
    WHERE SAL < (SELECT MAX(SAL) FROM EMP
        WHERE SAL < (SELECT MAX(SAL) FROM EMP
        )
    )
);

-- 64.WAQTD EMPNO OF THE EMPLOYEE EARNING 2D MAXIMUM SALARY
SELECT EMPNO FROM EMP
WHERE SAL = (SELECT MAX(SAL) FROM EMP
WHERE SAL < (SELECT MAX(SAL) FROM EMP));
-- 65. WAQTD DEPARTMENT NAME OF AN EMPLOYEE GETTING 4TH MAX SAL
SELECT DNAME 
FROM DEPT
WHERE DEPTNO IN (
    SELECT DEPTNO 
    FROM EMP 
    WHERE SAL = (
        SELECT MAX(SAL) FROM EMP
        WHERE SAL < (
            SELECT MAX(SAL) FROM EMP
            WHERE SAL < (
                SELECT MAX(SAL) FROM EMP
                WHERE SAL < (
                    SELECT MAX(SAL) FROM EMP
                )
            )
        )
    )
);
-- 66. WAQTD DETAILS OF THE EMPLOYEE WHO WAS HIRED 2nd 
SELECT * FROM EMP
WHERE HIREDATE = (SELECT MIN(HIREDATE) FROM EMP 
WHERE HIREDATE > (SELECT MIN(HIREDATE) FROM EMP)
);
--67.WAQTD NAME OF THE EMPLOYEE HIRED BEFORE THE LAST EMPLOYEE
SELECT ENAME FROM EMP
WHERE HIREDATE = (SELECT MAX(HIREDATE) FROM EMP
WHERE HIREDATE < (SELECT MAX(HIREDATE) FROM EMP)
);
-- 68. WAQTD LOC OF THE EMPLOYEE WHO WAS HIRED FIRST
SELECT LOC FROM DEPT
WHERE DEPTNO IN(SELECT DEPTNO FROM EMP
WHERE HIREDATE = (SELECT MIN(HIREDATE) FROM EMP
));
-- 69. WAQTD DETAILS OF THE EMPLOYEE EARNING 7TH MINIMUM SALARY
SELECT *
FROM EMP
WHERE SAL = (
    SELECT MIN(SAL) FROM EMP
    WHERE SAL > (
SELECT MIN(SAL) FROM EMP
        WHERE SAL > (
SELECT MIN(SAL) FROM EMP
            WHERE SAL > (
SELECT MIN(SAL) FROM EMP
                WHERE SAL > (
SELECT MIN(SAL) FROM EMP
                    WHERE SAL > (
SELECT MIN(SAL) FROM EMP
                        WHERE SAL > (
 SELECT MIN(SAL) FROM EMP
                        )
                    )
                )
            )
        )
    )
);
-- 70. WAQTD DNAME OF EMPLOYEE GETTING 2ND MAXIMUM SALARY
SELECT DNAME 
FROM DEPT
WHERE DEPTNO IN (
SELECT DEPTNO FROM EMP
WHERE SAL = (
        SELECT MAX(SAL) FROM EMP
WHERE SAL < (SELECT MAX(SAL) FROM EMP)
    )
);



-- ASSIGNMENT ON EMP AND MANAGER RELATION .

-- 71.WAQTD SMITHS REPORTING MANAGER'S NAME
SELECT ENAME FROM EMP
WHERE EMPNO = (SELECT MGR FROM EMP WHERE ENAME='SMITH');
-- 72.WAQTD ADAMS MANAGER'S MANAGER NAME
SELECT ENAME FROM EMP
WHERE EMPNO = (SELECT MGR FROM EMP 
WHERE EMPNO = (SELECT MGR FROM EMP WHERE ENAME='ADAMS'));
-- 73.WAQTD DNAME OF JONES MANAGER
SELECT DNAME FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP
WHERE EMPNO = (SELECT MGR FROM EMP WHERE ENAME='JONES'));
-- 74.WAQTD MILLER'S MANAGER'S SALARY
SELECT SAL FROM EMP
WHERE EMPNO = (SELECT MGR FROM EMP WHERE ENAME = 'MILLER');
-- 75.WAQTD LOC OF SMITH'S MANAGER'S MANAGER.
SELECT LOC FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP
WHERE EMPNO = (SELECT MGR FROM EMP
WHERE EMPNO = (SELECT MGR FROM EMP WHERE ENAME='SMITH')));
-- 76.WAQT DNAME OF THE EMPLOYEES REPORTING TO BLAKE
SELECT  DNAME FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP
WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME='BLAKE' ));
-- 77.WAQTD NUMBER OF EMPLPOYEES REPORTING TO KING
SELECT COUNT(*) FROM EMP
WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME='KING');
--  78.WAQTD DETAILS OF THE EMPLOYEES REPORTING TO JONES
SELECT * FROM EMP
WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME='JONES');
-- 79.WAQTD ENAMES OF THE EMPLOYEES REPORTING TO BLAKE'S MANAGER
SELECT ENAME FROM EMP
WHERE MGR = (SELECT MGR FROM EMP WHERE ENAME='BLAKE');
-- 80) NUMBER OF EMPLOYEES REPORTING TO FORD'S MANAGER
SELECT COUNT(*) FROM EMP
WHERE MGR = (SELECT MGR FROM EMP WHERE ENAME='FORD');

-- <<<<THEORY QUESTIONS ON JOINS >>>>>>

-- 121) WHAT IS JOINS LIST ALL THE TYPES OF JOINS ?
-- 122) WHAT IS CROSS JOIN EXPLAIN WITH SYNTAX ?
-- 123) WHAT IS INNER JOIN EXPLAIN WITH SYNTAX ?
-- 124) DIFFERENCES BETWEEN CROSS JOIN AND INNER JOIN ?
-- 125) EXPLAIN THE ADVANTAGES AND DISADVANTAGES OF INNER JOIN ?
-- 126) EXPLAIN THE NATURAL JOIN WITH SYNTAX ?
-- 127) WHAT IS OUTER JOIN EXPLAIN ALL OUTER JOIN WITH SYNTAX ?
-- 129) DIFFERENCES BETWEEN LOJ AND ROJ ?
-- 129) WHAT IS SELF JOIN EXPLAIN WITH SYNTAX ?
-- 130) WHAT IS THE USE USING SELF JOIN COMPARE TO SUB QUERY ? 



--    ASSIGNMENT ON INNER JOINS  OR NATURAL JOIN 


-- 131) WAQTD ENAME AND DNAME FOR ALL THE EMPLOYEES ?
SELECT ENAME, DNAME 
FROM EMP E , DEPT D
WHERE E.DEPTNO IN D.DEPTNO;
-- 132) WAQTD DNAME AND SAL FOR THE EMPLOYEES WHO ARE
--     WORKING AS MANAGER ?
SELECT DNAME , SAL
FROM EMP E , DEPT D
WHERE E.DEPTNO IN D.DEPTNO AND JOB = 'MANAGER';
-- 133) WAQTD SAL AND HIREDATE AND LOC FOR THE EMPLOYEES 
--     WHOSE NAME HAVING A CHARACTER IN THEIR NAME  ?
SELECT SAL, HIREDATE, LOC
FROM EMP E , DEPT D
WHERE E.DEPTNO IN D.DEPTNO AND ENAME LIKE '%A%';
-- 134) WAQTD ALL THE DETAILS OF AN EMPLOYEE ALONG WITH LOC FOR 
--     AN EMPLOYEES  WHOSE SAL IS MORE THEN 2000 IN ACCOUNTING DEPARTMENT ?
SELECT E.*, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO IN D.DEPTNO AND E.SAL > 2000 AND D.DNAME = 'ACCOUNTING';
-- 135) WAQTD DNAME AND SAL AND DEPTNO OF AN EMPLOYEES 
--     WHOSE JOB IS PRESIDENT  IN DEPTNO 10 ?
SELECT E.SAL, D.DNAME, D.DEPTNO
FROM EMP E , DEPT D
WHERE E.DEPTNO IN D.DEPTNO AND E.JOB ='PRESIDENT' AND D.DEPTNO=10;
-- 136) WAQTD ENAME AND DEPTNO AND LOC FOR ALL THE EMPLOYEES  
--     WHOSE NAME ENDS  WITH VOWELS ?
SELECT E.ENAME, D.LOC, D.DEPTNO
FROM EMP E , DEPT D
WHERE E.DEPTNO IN D.DEPTNO AND  regexp_like (E.ENAME, '.*[A,E,I,O,U]$');
-- 137) WAQTD HIREDATE AND DEPTNO FOR ALL THE EMPLOYEES WHO 
--      ARE WORKING IN  NEW YORK AND HAVING COMM ?
-- SELECT HIREDATE, DEPTNO
-- FROM EMP
-- NATURAL JOIN DEPT
-- WHERE LOC = 'NEW YORK' AND COMM IS NOT NULL;

SELECT E.HIREDATE, E.DEPTNO
FROM EMP E, DEPT D
WHERE E.DEPTNO IN D.DEPTNO AND D.LOC = 'NEW YORK' AND E.COMM IS NOT NULL;
-- 138) WAQTD EMPLOYEE NAME AND DEPARTMENT NAME FOR ALL
--     THE EMPLOYEE WHO  ARE HIRED IN THE MONTH OF FEB
--       INTO ACCOUNTING  DEPARTMENT ?
SELECT ENAME, DNAME
FROM EMP
NATURAL JOIN DEPT
WHERE  DNAME IN ('ACCOUNTING');
-- 139) WAQTD LOC AND EMPNO AND MGR NO FOR ALL THE EMPLOYEES 
--      WHOSE SAL LESS THEN 5000 IN BOSTON HIRED IN THE YEAR OF 87 ?

-- 140) WAQTD DNAME AND LOC ALONG WITH 10% HIKE IN THE 
--     SALARY OF AN EMPLOYEE   WHO ARE REPORTING TO ALLEN ?
SELECT D.DNAME, D.LOC,  E.SAL*1.1 "HIKE"
FROM EMP E , DEPT D
WHERE E.DEPTNO = D.DEPTNO
 AND E.MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'ALLEN');

-- SELECT D.DNAME, D.LOC, E.SAL * 1.1 AS HIKE
-- FROM EMP E, DEPT D
-- WHERE E.DEPTNO = D.DEPTNO
-- AND E.MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'ALLEN');
-- 141) WAQTD ANNAUL SALARY AND LOC OF AN EMPLOYEE 
--      WHOSE MANAGER NAME IS KING ?
SELECT SAL*12 ASAL, LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO IN D.DEPTNO AND E.MGR = (SELECT EMPNO FROM EMP WHERE ENAME='KING');
-- 142) WAQTD ALL TEH DETAILS OF AN EMPLOYEES AND THEIR DNAME AND  LOC  FOR                               
--       THE EMPLOYEE WHOSE COMM IS NULL IN DEPTNO 10,20  ?
SELECT E.*, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND COMM IS  NULL AND D.DEPTNO IN (10,20);
-- 143) WAQTD DNAME AND ENAME FOR THE EMPLOYEE WHOSE SALARY ENDS 
--      WITH 50  IN DEPTNO 10,20,30 AND WORKING IN RESEARCH DEPARTMENT ?
SELECT D.DNAME , E.ENAME
FROM  EMP E, DEPT D
WHERE E.SAL LIKE  '%50' AND E.DEPTNO IN (10,20,30) AND D.DNAME ='RESEARCH';
-- 144) WAQTD LOC DNAME  AND ENAME OF AN EMPLOYEES WHO 
--       ARE HIRED BEFORE THE LAST TWO EMPLOYEES ?
SELECT D.LOC, D.DNAME, E.ENAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND E.HIREDATE < (SELECT MAX(HIREDATE) FROM EMP WHERE HIREDATE < (SELECT MAX(HIREDATE) FROM EMP ) );
-- 145) WAQTD DNAME AND SALARY OF AN EMPLOYEE WHOSE 
--      NAME ENDS WITH CONSONANTS ?
SELECT D.DNAME, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND  REGEXP_LIKE (ENAME, '.*[^A,E,I,O,U]$');
-- 146) WAQTD MGR SAL AND DEPTNO AND LOC OF AN EMPLOYEES WHOSE LOC ENDS WITH S ?
SELECT E.MGR, E.SAL, E.DEPTNO , D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND LOC LIKE '%S';
-- 147) WAQTD EMPNO AND LOC FOR THE EMPLOYEES WHOSE HIREDATE IS '01-JAN-81' IN DALLAS ?
SELECT E.EMPNO, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND HIREDATE = '01-JAN-1981' AND LOC = 'DALLAS';
-- 148) WAQTD ENAME AND LOC AND SAL OF AN EMPLOYES WHOSE EMPNO ARE 7369,7488 ?
SELECT E.ENAME, D.LOC , E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND EMPNO IN (7369,7488);
-- 149) WAQTD ENAME AND LOC FOR THE EMPLOYEES WHOSE SAL IS LESS THEN KING 
--     AND MORE THEN SMITH IN DEPTNO 30 AND WORKING IN SALES DEPARTMENT ?
SELECT E.ENAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO= D.DEPTNO AND SAL < (SELECT SAL FROM EMP WHERE ENAME='KING') 
AND SAL > (SELECT SAL FROM EMP WHERE ENAME='SMITH') 
AND E.DEPTNO = 30
AND D.DNAME = 'SALES';
-- 150) WAQTD COMM AND LOC FOR THE EMPLOYEES WHOSE MGR IS 7902 WORKING IN
--     ACCOUNTING AND RESEARCH DEPARTMENT ?
SELECT E.COMM, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND E.MGR = 7902 AND DNAME IN ('ACCOUNTING', 'RESEARCH');

------------------------------  THIS IS THE QUESTION 130 TO 150 FOR NATURAL JOIN -----------------------------------------------

-- 131) WAQTD ENAME AND DNAME FOR ALL THE EMPLOYEES ?
SELECT ENAME, DNAME
FROM EMP
NATURAL JOIN DEPT;

-- 132) WAQTD DNAME AND SAL FOR THE EMPLOYEES WHO ARE WORKING AS MANAGER ?
SELECT DNAME, SAL
FROM EMP
NATURAL JOIN DEPT
WHERE JOB = 'MANAGER';

-- 133) WAQTD SAL AND HIREDATE AND LOC FOR THE EMPLOYEES WHOSE NAME HAVING A CHARACTER IN THEIR NAME ?
SELECT SAL, HIREDATE, LOC
FROM EMP
NATURAL JOIN DEPT
WHERE ENAME LIKE '%A%';

-- 134) WAQTD ALL THE DETAILS OF AN EMPLOYEE ALONG WITH LOC FOR AN EMPLOYEES WHOSE SAL IS MORE THEN 2000 IN ACCOUNTING DEPARTMENT ?
SELECT E.*, LOC
FROM EMP E , DEPT D
WHERE E.DEPTNO = D.DEPTNO AND SAL > 2000 AND DNAME = 'ACCOUNTING';

-- 135) WAQTD DNAME AND SAL AND DEPTNO OF AN EMPLOYEES WHOSE JOB IS PRESIDENT IN DEPTNO 10 ?
SELECT DNAME, SAL, DEPTNO
FROM EMP
NATURAL JOIN DEPT
WHERE JOB = 'PRESIDENT' AND DEPTNO = 10;

-- 136) WAQTD ENAME AND DEPTNO AND LOC FOR ALL THE EMPLOYEES WHOSE NAME ENDS WITH VOWELS ?
SELECT ENAME, DEPTNO, LOC
FROM EMP
NATURAL JOIN DEPT
WHERE REGEXP_LIKE(ENAME, '.*[AEIOU]$');

-- 137) WAQTD HIREDATE AND DEPTNO FOR ALL THE EMPLOYEES WHO ARE WORKING IN NEW YORK AND HAVING COMM ?
SELECT HIREDATE, DEPTNO
FROM EMP
NATURAL JOIN DEPT
WHERE LOC = 'NEW YORK' AND COMM IS NOT NULL;

-- 138) WAQTD EMPLOYEE NAME AND DEPARTMENT NAME FOR ALL THE EMPLOYEE WHO ARE HIRED IN THE MONTH OF FEB INTO ACCOUNTING DEPARTMENT ?
SELECT ENAME, DNAME
FROM EMP
NATURAL JOIN DEPT
WHERE DNAME = 'ACCOUNTING'
AND TO_CHAR(HIREDATE,'MON') = 'FEB';

-- 139) WAQTD LOC AND EMPNO AND MGR NO FOR ALL THE EMPLOYEES WHOSE SAL LESS THEN 5000 IN BOSTON HIRED IN THE YEAR OF 87 ?
SELECT LOC, EMPNO, MGR
FROM EMP
NATURAL JOIN DEPT
WHERE SAL < 5000
AND LOC = 'BOSTON'
AND TO_CHAR(HIREDATE,'YY') = '87';

-- 140) WAQTD DNAME AND LOC ALONG WITH 10% HIKE IN THE SALARY OF AN EMPLOYEE WHO ARE REPORTING TO ALLEN ?
SELECT DNAME, LOC, SAL*1.1 "HIKE"
FROM EMP  NATURAL JOIN DEPT
WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'ALLEN');

-- 141) WAQTD ANNUAL SALARY AND LOC OF AN EMPLOYEE WHOSE MANAGER NAME IS KING ?
SELECT SAL*12 ASAL, LOC
FROM EMP  NATURAL JOIN DEPT
WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'KING');



-- 143) WAQTD DNAME AND ENAME FOR THE EMPLOYEE WHOSE SALARY ENDS WITH 50 IN DEPTNO 10,20,30 AND WORKING IN RESEARCH DEPARTMENT ?
SELECT DNAME, ENAME
FROM EMP
NATURAL JOIN DEPT
WHERE SAL LIKE '%50'
AND DEPTNO IN (10,20,30)
AND DNAME = 'RESEARCH';

-- 144) WAQTD LOC DNAME AND ENAME OF AN EMPLOYEES WHO ARE HIRED BEFORE THE LAST TWO EMPLOYEES ?
SELECT LOC, DNAME, ENAME
FROM EMP
NATURAL JOIN DEPT
WHERE HIREDATE < (
SELECT MAX(HIREDATE)
FROM EMP
WHERE HIREDATE < (SELECT MAX(HIREDATE) FROM EMP)
);

-- 145) WAQTD DNAME AND SALARY OF AN EMPLOYEE WHOSE NAME ENDS WITH CONSONANTS ?
SELECT DNAME, SAL
FROM EMP
NATURAL JOIN DEPT
WHERE REGEXP_LIKE(ENAME, '.*[^AEIOU]$');

-- 146) WAQTD MGR SAL AND DEPTNO AND LOC OF AN EMPLOYEES WHOSE LOC ENDS WITH S ?
SELECT MGR, SAL, DEPTNO, LOC
FROM EMP
NATURAL JOIN DEPT
WHERE LOC LIKE '%S';

-- 147) WAQTD EMPNO AND LOC FOR THE EMPLOYEES WHOSE HIREDATE IS '01-JAN-81' IN DALLAS ?
SELECT EMPNO, LOC
FROM EMP
NATURAL JOIN DEPT
WHERE HIREDATE = '01-JAN-1981'
AND LOC = 'DALLAS';

-- 148) WAQTD ENAME AND LOC AND SAL OF AN EMPLOYES WHOSE EMPNO ARE 7369,7488 ?
SELECT ENAME, LOC, SAL
FROM EMP
NATURAL JOIN DEPT
WHERE EMPNO IN (7369,7488);

-- 149) WAQTD ENAME AND LOC FOR THE EMPLOYEES WHOSE SAL IS LESS THEN KING AND MORE THEN SMITH IN DEPTNO 30 AND WORKING IN SALES DEPARTMENT ?
SELECT ENAME, LOC 
FROM EMP NATURAL JOIN DEPT
WHERE SAL < (SELECT SAL FROM EMP WHERE ENAME='KING') AND 
SAL > (SELECT SAL FROM EMP WHERE ENAME='SMITH')
AND DEPTNO=30 AND DNAME='SALES';


-- 150) WAQTD COMM AND LOC FOR THE EMPLOYEES WHOSE MGR IS 7902 WORKING IN ACCOUNTING AND RESEARCH DEPARTMENT ?
SELECT COMM, LOC
FROM EMP
NATURAL JOIN DEPT
WHERE MGR = 7902
AND DNAME IN ('ACCOUNTING','RESEARCH');











--- >>>>>>>> ASSIGNMENT ON  OTHER JOINS>>>>>>>>>>

-- 151) WAQTD ENAME AND DNAME FOR ALL THE EMPLOYEES OF THE EMPLOYEES NOT WORKING IN ANY DEPARTMENT ?
SELECT ENAME, DNAME 
FROM EMP E , DEPT D
WHERE E.DEPTNO = D.DEPTNO(+)
AND D.DEPTNO IS NULL;

SELECT ENAME, DNAME
FROM EMP E LEFT JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
AND D.DEPTNO IS NULL;

-- 152) WAQTDALL THE DETAILS OF AMPLOYEES AND THEIR DEPARTMENT DETAILS IF THE DEPARTMENT IN WHICH NO EMPLOYEES ARE 
-- WORKING ?
SELECT *
FROM EMP E , DEPT D
WHERE E.DEPTNO(+) = D.DEPTNO
AND E.DEPTNO IS  NULL;

SELECT  *
FROM EMP E RIGHT JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
AND E.DEPTNO IS NULL;
-- 153) WAQTD ALL THE DETAILS OF AN EMPLOYEES AND HIER DEPARTMENT DETAILS IF THE EMPLOYEES NOT WORKING IN ANY DEPARTMENT AND THE DEPARTMENT IN WHICH THE NO EMPLOYEES ARE  WORKING ?
SELECT *
FROM EMP E FULL JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.DEPTNO IS NULL OR D.DEPTNO IS NULL;


-- 154) WAQTD ENAME AND SAL AND DNAME FOR THE EMPLOYEES THOSE WHO ARE NOT WORKING IN ANY DEPARTMENT ?
SELECT ENAME , SAL , DNAME
FROM EMP E , DEPT D
WHERE E.DEPTNO = D.DEPTNO(+)
AND D.DEPTNO IS NULL;

SELECT ENAME ,SAL, DNAME
FROM EMP E LEFT JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE D.DEPTNO IS NULL;

-- 155) WAQTD HIERDATE AND JOB INCLUDING DNAME AND LOC FOR THE DEPARTMENT IN WHICH NO EMPLOYEES ARE WORKING  ?
SELECT HIREDATE, JOB, DNAME, LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO(+) = D.DEPTNO
AND E.DEPTNO IS NULL;


SELECT HIREDATE, JOB, DNAME, LOC
FROM EMP E RIGHT JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.DEPTNO IS NULL;
-- 156) WAQTD DNAME AND LOC AND JOB FOR THE EMPLOYEES WHO ARE NOT WORKING IN ANY DEPARTMENT AND THE DEPARTMENT NO EMPLOYEES ARE WORKING ?
SELECT DNAME, LOC, JOB
FROM EMP E FULL JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.DEPTNO IS NULL OR D.DEPTNO IS NULL;
-- 157) WAQTD EMPLOYEES NAME AND DEPTNAME FOR ALL THE EMPLOYEES 
-- WHOSE SALARIES ARE MORE THEN 2000 ?
SELECT ENAME, DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO(+)
AND E.SAL > 2000;

SELECT ENAME, DNAME
FROM EMP E LEFT JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.SAL >2000;
-- 158) WAQTDMANAGER NAME AND THE EMPLOYEES SALARY FOR ALL THE EMPLOYEES THOSE WHO ARE WORKING IN DEPTNO 10,20 ?
SELECT E.SAL, M.ENAME
FROM EMP E ,  EMP M
WHERE E.MGR = M.EMPNO AND E.DEPTNO IN (10,20);
-- 159) WAQTD MANAGERS MANAGER NAME FOR ALL THE MANAGER WHOSE SALARIES ARE LESS THEN EMPLOYES ?
SELECT MM.ENAME
FROM EMP E, EMP M, EMP MM
WHERE E.MGR = M.EMPNO AND
    M.MGR = MM.EMPNO AND
    E.SAL > M.SAL ;
-- 160) WAQTD EMPLOYEES NAME MANAGER SALARY AND MANAGER MANAGER COMM FOR ALL THE MANAGER WHO HIRED BEFORE THE 87 AS SALESMAN
-- AND EARNING SALARY MORE THEN MANAGERS MANAGER ?
SELECT E.ENAME, M.SAL, MM.COMM
FROM EMP E, EMP M, EMP MM
WHERE E.MGR = M.EMPNO AND M.HIREDATE < '01-JAN-1987' AND M.JOB = 'SALESMAN' AND
      M.MGR = MM.EMPNO  AND M.SAL > MM.SAL;
-- 161) WAQTD ENAME AND MANAGER HIREDATE AND JOB FOR ALL THE EMPLOYEES WHO ARE WORKING IN NEW YORK ?
SELECT E.ENAME, M.HIREDATE , E.JOB
FROM EMP E , EMP M, DEPT ED
WHERE E.MGR = M.EMPNO  AND E.DEPTNO = ED.DEPTNO AND ED.LOC = 'NEW YORK';
-- 162) WAQTD EMPLOYEES DNAME AND MANAGER LOC INCLUDING EMPLOYEES SALARY AND MANAGER DEPTNO FOR ALL THE EMPLOYEES WHO ARE HIRED BEFORE THE MANAGERS MANAGE ?
SELECT MD.DNAME, ED.LOC , E.SAL, M.DEPTNO
FROM EMP E, EMP M , DEPT ED, EMP MM, DEPT MD
WHERE E.MGR = M.EMPNO AND E.DEPTNO = MD.DEPTNO AND M.DEPTNO = ED.DEPTNO AND M.MGR = MM.EMPNO AND E.HIREDATE < MM.HIREDATE;
-- 163) WAQTD MANAGERS MANAGER NAME FOR ALL THE EMPLOYEES WHO ARE WORKING IN MANAGERS LOCATION AND NOT WORKING IN MANAGES MANAGERS LOCATION ?
SELECT MM.ENAME
FROM EMP E, EMP M, EMP MM, DEPT ED, DEPT MMD, DEPT MD
WHERE E.MGR = M.EMPNO 
AND M.MGR = MM.EMPNO 
AND M.DEPTNO = MD.DEPTNO 
AND E.DEPTNO = ED.DEPTNO 
AND MM.DEPTNO = MMD.DEPTNO 
AND ED.LOC = MD.LOC 
AND ED.LOC <> MMD.LOC;
-- 164) WAQTD MANAGER NAME FOR THE MANAGERS MANAGER WHO ARE WORKING IN DEPTNO 20 AS ACTUAL MANAGER AND EARNING SALARY MORE THEN THE EMPLOYEES ?
SELECT M.ENAME
FROM EMP E , EMP M , EMP MM
WHERE E.MGR = M.EMPNO 
AND   M.MGR = MM.EMPNO
AND  M.SAL > E.SAL
AND M.DEPTNO = 20;
-- 165) WAQTD MANAGERS DNAME AND MANAGERS MANAGER LOC FOR THE EMPLOYEES WHO ARE WORKING IN BOSTON ?
SELECT MD.DNAME, MMD.LOC
FROM EMP  E, EMP M , DEPT ED, DEPT MD, EMP MM, DEPT MMD
WHERE E.MGR = M.EMPNO
AND   M.MGR = MM.EMPNO
AND     MM.DEPTNO = MMD.DEPTNO
AND   E.DEPTNO = ED.DEPTNO
AND   M.DEPTNO = MD.DEPTNO
AND   ED.LOC='BOSTON';
-- 166) WAQTD EMPLOYEES DNAME FOR THE MANAGERS MANAGER WHOSE SAL ARE MORE THAN MANAGER AND LESS THAN EMPLOYEES ?
SELECT  ED.DNAME
FROM EMP E, EMP M ,EMP MM, DEPT ED
WHERE E.MGR = M.EMPNO
AND M.MGR = MM.EMPNO
AND E.DEPTNO = ED.DEPTNO
AND MM.SAL > M.SAL 
AND MM.SAL < E.SAL;
-- 167) WAQTD EMPLOYEES LOC AND MANAGERS MANAGERS LOC FOR THE MANAGER WHO ARE HIRED BEFORE THE EMPLOYEE AND EARNING SALARY MORE THAN THE EMPLOYEES ?
SELECT ED.LOC , MMD.LOC
FROM EMP E, EMP M, EMP MM, DEPT ED, DEPT MMD
WHERE E.MGR = M.EMPNO
AND   M.MGR = MM.EMPNO
AND  E.DEPTNO = ED.DEPTNO
AND MM.DEPTNO = MMD.DEPTNO
AND M.HIREDATE < E.HIREDATE
AND M.SAL > E.SAL;
-- 168) WAQTD MANAGERS MANAGERS MANAGER NAME FOR THE EMPLOYEES WHO ARE WORKING IN MANAGERS MANAGERS MANAGERS LOC AND EARNING SALARY LESS THE MANAGERS HIRED BEFORE MANAGERS MANAGERS MANAGER ?
SELECT MMM.ENAME
FROM EMP E, EMP M, EMP MM, EMP MMM,  DEPT MMMD, DEPT ED
WHERE E.MGR = M.EMPNO
AND M.MGR = MM.EMPNO
AND MM.MGR = MMM.EMPNO
AND MMM.DEPTNO = MMMD.DEPTNO
AND E.DEPTNO = ED.DEPTNO
AND ED.LOC = MMMD.LOC
AND E.SAL < M.SAL
AND M.HIREDATE < MMM.HIREDATE;



-- 169) WAQTD DNAME FOR THE EMPLOYEES WHO HIRED BEFORE  THE MANAGERS INTO ACCOUNTING DEPARTMENT IN THE MONTH OF DEC ?
SELECT ED.DNAME
FROM EMP E, EMP M, DEPT ED, DEPT MD
WHERE E.MGR= M.EMPNO
AND E.DEPTNO = ED.DEPTNO
AND M.DEPTNO = MD.DEPTNO
AND E.HIREDATE < M.HIREDATE
AND MD.DNAME = 'ACCOUNTING'
AND E.HIREDATE LIKE '%87';
-- 170) WAQTD MANAGERS MANAGERS MANAGERS MANAGER NAME IF THEY ARE HIRED AFTER THE MANAGERS INTO DALLAS ?
SELECT DISTINCT MMM.ENAME
FROM EMP E, EMP M, EMP MM, EMP MMM, DEPT MD
WHERE E.MGR = M.EMPNO
AND M.MGR = MM.EMPNO
AND MM.MGR = MMM.EMPNO
AND M.DEPTNO = MD.DEPTNO
AND MD.LOC = 'DALLAS'
AND MMM.HIREDATE > M.HIREDATE;







-- ADDED QUESTIONS ON OTHER JOINS  
-- WAQTD ENAME ,LOC , AND SAL OF ALL THE EMPLOYEES EVEN IF THEY NOT ASSIGNED TO ANY DEPARTMENT . WORKING AS SALESMAN AND EARNING SALARY MORE THEN 1000 ? 
SELECT E.ENAME, D.LOC , E.SAL
FROM EMP E LEFT JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE  E.JOB = 'SALESMAN' AND E.SAL > 1000;
-- WAQTD ENAME ,LOC ,DNAME  AND SAL OF ALL THE DEPARTMENTS EVEN IN THAT THERE IS NO EMPLOYEES ARE WORKING AND LOC BELONGS TO NEW YORK ?
SELECT ENAME, LOC, DNAME, SAL
FROM EMP E RIGHT JOIN DEPT D
ON E.DEPTNO =  D.DEPTNO
AND D.LOC = 'NEW YORK';

SELECT ENAME, LOC, DNAME, SAL
FROM EMP E , DEPT D
WHERE E.DEPTNO(+) =  D.DEPTNO
 AND D.LOC = 'NEW YORK';
-- WAQTD ENAME ,LOC , AND DNAME ,HIREDATE  SAL OF ALL THE EMPLOYEES EVEN IF THEY NOT ASSIGNED TO ANY DEPARTMENT . WORKING AS SALESMAN AND WHOSE NAME STARTS WITH CONSONANTS  ?
SELECT E.ENAME, D.LOC, D.DNAME, E.HIREDATE, E.SAL
FROM EMP E
LEFT JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.JOB = 'SALESMAN'
AND E.SAL IS NOT NULL
AND NOT REGEXP_LIKE (E.ENAME , '^[AEIOU].*');   



SELECT E.ENAME, D.LOC, D.DNAME, E.HIREDATE, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO(+)
AND E.JOB = 'SALESMAN'
AND E.SAL IS NOT NULL
AND NOT REGEXP_LIKE (E.ENAME , '^[AEIOU].*'); 
-- WAQTD ALL THE EMPLOYEES DETAILS AND THEIR DEPARTMENT DETAILS EVEN THE EMPLOYEES ARE NOT ASSIGNED TO ANY LOCATION 
-- IF DEPARTMENT NAME HAVING A CHARACTERS 
SELECT *
FROM EMP E
LEFT JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
AND D.DNAME LIKE '%A%'; 

SELECT *
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO(+)
AND D.DNAME(+) LIKE '%A%';













-- SCENARIO BASED QUESTIONS 
-- ASSUME STD TABLE AND TRAINER TABLE 
-- STD —(  SID , SNAME , DOB , MNO , COURSE ,TID (FK)) CHILD TABLE
-- TRN –(TID(PK),TNAME ,SAL, HQUALIFICATION,BRANCH) PARENT TABLE
-- Q1. WAQTD SNAME , DOB , TNAME ,BRANCH FOR ALL THE STUDENTS EVEN THE STD ARE NOT ASSIGNED TO ANY TRAINERS  ?
-- Q2.WAQTD ALL THE STUDENTS DETAILS AND THEIR TRAINERS DETAILS 
--    FOR ALL TRAINER EVEN THE TRAINER THEY ARE NOT ASSIGNED TO ANY  STUDENTS ?
-- Q3.WAQTD ALL THE TRAINERS AND STUDENTS DETAILS EVEN THE STUDENTS WHO ARE NOT ASSIGNED TO ANY TRAINERS AND ALSO THE TRAINERS WHO ARE NOT ASSIGNED TO ANY STUDENTS ?

-- ASSUME DOCTOR AND PATIENT TABLES 
-- DOCTOR —- (DID ,DNAME , MNO ,SPEC,EXP)  — PARENT TABLE 
-- PATIENT — (PID ,PNAME , DOB , MNO , GMAIL, ADDRESS) — CHILD TABLE 
-- Q1. WAQME , PID DNAME , PNADRESS FOR ALL THE DOCTORS EVEN THE DOCTORS ARE 
-- NOT ASSIGNED TO ANY PATIENT ?
-- Q2. WAQTD ALL THE DOCTORS DETAILS AND PATIENT DETAILS FOR ALL THE PATIENT EVEN THE PATIENT ARE NOT ASSIGNED TO ANY DOCTORS AND THE PATIENT ADDRESS IS PUNE ?
-- Q3. WAQTD ALL THE DOCTORS DETAILS AND PATINETS DETAILS EVEN THE DOCTORS ARE NOT ASSIGNED TO ANY PATIENT AND ALSO THE PATIENTS ARE NOT ASSIGNED TO ANY DOCTORS ?













-- >>>> ASSIGNMENT ON DDL DML TCL DCL >>>>
-- 171) WAQT CREATE ANY ONE TABLE WITHOUT ANY PRIMARY KEY WITH 5 COLUMNS ?
-- 172) WAQT RENAME THE EMP TABLE NAME TO EMPLOYEES  ?
-- 173) WAQT TRUNCATE THE SALGRADE TABLE  ?
-- 174) WAQT DROP THE EMP ANY ONE TABLE FROM DATABASE AND GET IT BACK  ?
-- 175) WAQT PURGE THE ANY ONE TABLE  ?
-- 176) WAQT CREATE TWO TABLES AND MAKE  THE CONNECTION BETWEEN THESE TWO TABLES  ?
-- 177) WAQT ADD THE ONE COLUMN INTO EMPLOYEES TABLE ?
-- 178) WAQT ADD TWO COLUMN INTO DEPT TABLE ?
-- 179) WAQT DROP THE RECENTLY ADDED COLUMN FROM THE EMP TABLE ?
-- 180) WAQT RENAME THE COLUMN FROM EMP AND DEPT TABLE  FOREIGN KEY AS DNO ?

-- 181) WAQT INSERT 5 RECORDS INTO EMP TABLE ?
-- 182) WAQT DELETE THE EMPLOYEES RECORD WHOSE NAME IS KING ?
-- 183) WAQT UPDATE THE SALARY OF SMITH AS 5000 ?
-- 184) WAQT  UPDATE THE JOB OF ALL THE EMPLOYEES AS MANAGER  WHO ARE GETTING SAL <1600 ?
-- 185) WAQT DELETE THE EMPLOYEES RECORD WHO ARE WORKING IN NEW YORK ?
-- 186) WAQT DELETE THE EMPLOYEES RECORDS WHO ARE EARNING SALARY MORE THEN  SMITH AND HIRED BEFORE SCOTT ?
-- 187) WAQT TO UPDATE THE COMM FOR ALL THE EMPLOYEES WHO ARE REPORTING TO KING  AS 1000 ?
-- 188) WAQT UPDATE THE JOB AS BOSS AND SALARY AS 90000 FOR THE EMPLOYEES WHOSE DNAME HAVING EXACTLY ONE A ?
-- 189) WAQT TAKE PERMISSION FROM THE SCOTT AND DELETE THE RECORDS WHOSE SALARY IS 3000  IN HR DATABASE ?
-- 190) WAQT RETAKE THE PERMISSION FROM HR AND TRY TO DELETE THE RECORDS WHOSE SAL IS MORE THEN 2000 ?







-- >>>>> THEORY  STATEMENT  QUESTIONS  >>>>>>
-- 191) WHAT ARE THE  DIFFERENCE BETWEEN DELETE AND TRUNCATE ?
-- 192) DIFFERENCE BETWEEN DELETE DROP AND TRUNCATE ?
-- 193) DIFFERENCE BETWEEN ALTER AND UPDATE ?
-- 194) SYNTAX FOR CREATE TABLE WITH PRIMARY KEY AND FOREIGN KEY ?
-- 195) SYNTAX FOR GRANT AND REVOKE ?
-- 196) SYNTAX FOR DML ?
-- 197) SYNTAX FOR ALL THE STATEMENT OF DDL ?
-- 198) SYNTAX FOR CHECK THE CONSTRAINTS ?
-- 199) SYNTAX FOR TO CHECK THE TABLE LIST FROM RECYCLE BIN ?
-- 20) SYNTAX FOR TO CHECK THE PERMISSION LIST ?
-- 201) SYNTAX FOR TCL STATEMENTS ?
-- 202) SYNTAX FOR SELECTION AND PROJECTION  ?
-- 203) DIFFERENCE BETWEEN PROJECTION AND SELECTION ?
-- 204) DIFFERENCE BETWEEN DDL AND DML ?
-- 205) SYNTAX FOR TO CREATE THE INDEX ?
-- 206) SYNTAX FOR TO CHECK THE STRUCTURE OF TABLE ?
-- 207) SYNTAX FOR TO ADD THE COLUMN INTO TABLE ?
-- 208) SYNTAX FOR TO DROP THE COLUMN FROM THE TABLE ?
-- 209) SYNTAX FOR TO CHANGE THE DATATYPES ?
-- 210) SYNTAX FOR TO CHANGE FROM NULL TO NOT NULL OR VISE VERSA ?















-- SRF QUESTIONS  /  ASSIGNMENT 


-- 211) WAQTD THE NO OF CHARACTERS PRESENT IN YOUR NAME ?
SELECT LENGTH('VISHWAJIT') MYNAME  FROM DUAL;
-- 212) WAQTD THE DEATILS OF THE EMPLOYEES WHOSE NAME HAVING 
--    4 CHARACTERS ?
SELECT * FROM EMP
WHERE LENGTH(ENAME)=4;
-- 213) WAQTD ENAME AND LOC OF ALL THE EMPLOYEES WHO ARE EARNING 4 DIGIT OF SALARY ?
SELECT ENAME, LOC FROM EMP E , DEPT D
WHERE  E.DEPTNO = D.DEPTNO AND LENGTH(SAL)=4;
-- 214) WAQT GET THE REMINDER VALUES OF 10 /5 ?
SELECT MOD(10,5) FROM DUAL;
-- 215) WAQTD THE DEATILS OF EMPLOYEES WHOSE NAME ENDS WITH VOWELS ?
SELECT *
FROM EMP
WHERE UPPER(SUBSTR(ENAME, -1)) IN ('A', 'E', 'I', 'O', 'U');
-- 216) WAQTD ALL THE DEATILS OF THE EMPLOYEES WHO AHEV MORE THEN 513 MONTHS 
--    OF EXPERIANCE ?
SELECT * FROM EMP
WHERE MONTHS_BETWEEN(SYSDATE, HIREDATE) > 513;
-- 217) WAQT REPLACE THE 3RD A FROM THE MALAYALAM ?
SELECT SUBSTR('MALAYALAM', 1, INSTR('MALAYALAM', 'A',1, 3)-1) || 'Z'|| 
SUBSTR('MALAYALAM', INSTR('MALAYALAM', 'A',1, 3)+1 ) FROM DUAL;
-- 218) WAQTD THE FIRST HALF NAME OF EMPLOYEES SAME AND 2ND HALF NAME 
--    OF EMPLOYEES IN REVERSE MANNAER ?
SELECT SUBSTR(ENAME, 1 ,LENGTH(ENAME)/2) || REVERSE(SUBSTR(ENAME, LENGTH(ENAME)/2+1)) FROM EMP;
-- 219) WAQT REPLACE THE FIRST 6 NUMBER AS (*) FROM 9900199001 ?
SELECT REPLACE(9900199001,SUBSTR( 9900199001,1,6),'******') FROM DUAL;
-- 220) WSQTD OF THE EMPLOYEES WHOSE NAME HAVING EXACTLY 2 A IN THEIR NAMES ?
SELECT *
FROM EMP
WHERE LENGTH(ENAME) - LENGTH(REPLACE(ENAME,'A','')) = 2;
-- 221) WAQTD DNAME AND SAL OF ALL THE EMPLOYEES WHOSE NAMES ARE PALYDROM IN NATURE ?
SELECT DNAME, SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND ENAME = REVERSE(ENAME);
-- 222) WAQTD DNAME AND ENAME OF ALL THE EMPLOYEES WHOSE 2ND HALF NAME PALYDROM IN NATURE ?
SELECT DNAME, ENAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND SUBSTR(ENAME, LENGTH(ENAME)/2 + 1) =
REVERSE(SUBSTR(ENAME, LENGTH(ENAME)/2 + 1));
-- 223) WAQTD THE TOTAL SALARY NEEDED TO PAY FOR EACH AND EVERY EMPLOYEES ?(NVL)
SELECT SUM(SAL + NVL(COMM,0))  TOTAL_PAYMENT
FROM EMP;
-- 224) WAQTD THE DETAILS OF THE EMPLOYEES WHO ARE EARNING 3RD MAX SALARY FROM EMP TABLE ?
SELECT *
FROM EMP
WHERE SAL = (
    SELECT MAX(SAL)
    FROM EMP
    WHERE SAL < (
        SELECT MAX(SAL)
        FROM EMP
        WHERE SAL < (
            SELECT MAX(SAL)
            FROM EMP
        )
    )
);
-- 225) WAQTD THE 2ND MAX SALARY FROM EACH AND EVERY JOB ?
SELECT JOB, MAX(SAL) AS SECOND_MAX_SAL
FROM EMP E
WHERE SAL < (
    SELECT MAX(SAL)
    FROM EMP
    WHERE JOB = E.JOB
)
GROUP BY JOB;
-- 226) WAQTD THE EMPLOYEES NAME AND THEIR DNAME IN INITCAP FORMAT 
--     AND ALSO DISPLAY THEIR JOB IN LOWER CASE FORMAT ?
SELECT INITCAP(ENAME), INITCAP(DNAME), LOWER(JOB)
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;
-- 227) WAQT GET THE NO OF MONTHS BETWEEN YOUR DATE OF BIRTH TO TODAYS DATE ?
SELECT MONTHS_BETWEEN(SYSDATE,'25-JUN-2004')
FROM DUAL;
-- 228) WAQT GET THE YOUR CURRENT AGE IN YEAR FORMAT UPTO THE DATE ?
SELECT TRUNC(MONTHS_BETWEEN(SYSDATE,'25-JUN-2004')/12)
FROM DUAL;
-- 229) WAQT CONCAT ENAME WITH THEIR  HALF DNAME OF ALL THE EMPLOYEES ?
SELECT ENAME || SUBSTR(DNAME,1,LENGTH(DNAME)/2)
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;
-- 230) WAQT GET THE DEATILS OF THE EMPLOYEES IF THEIR NAME HAVING % AS LAST LETTER ?
-- 231) WAQTD THE DETAILS OF AN EMPLOYEES IF THEIR SALARIES ARE PALYDROM IN NATURE ?
-- 232) WAQTD ALL THE EMPLOYEES IF THEIR NAME AND DNAME STARST WITH SAME LETTER ?
-- 233) WAQTD ALL THE EMPLOYEES IF THEIR NAME AND DNAME STARST AND ENDS WITH SAME LETTER ?
-- 234) WAQTD THE LOC AND DNAME AND JOB OF ALL THE EMPLOYEES IF THEIR NAME MIDDLE 
--     LETTERS ARE VOWELS ?
-- 235) WAQT GET EXACTLY THE MIDDLE NAME FROM  "VIRAT ANUSKHA KHOLI" ?
-- 236) WAQT PRINT THE DEATILS IN GIVEN FLOW 
--     "HI SMITH GOOD MORNING YOUR DESIGNATION IS CLERK AND SALARY IS 800 YOUR 
--     DEPTNO IS 20"  SAME FORMAT FOR ALL THE EMPLOYEES  ?
-- 237) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE HIRED ON WENSEDAY ?
-- 238) WAQTD ALL THE DEATILF OF EMPLOYEES AND THEIR DEPARTMENT IF THEY ARE 
--     HIRED IN THE MONTH OF DEC , JAN , FEB ?
-- 239) WAQTD ALL THE EMPLOYEES IF THEY ARE HIRED IN THE YEAR OF 81, 87, 82 ?
-- 240) WAQT GET THE YOUR CURRENT AGE WITH DAY OF BORN ?




--  DIFFERENCES QUESTIONS IN SQL 
-- 241) DIFFERENCES BETWEEN DMBS AND RDBMS ?
-- 242) DIFFERENCES BETWEEN CHAR AND VARCHAR ?
-- 243) DIFFERENCES BETWEEN SQL AND NO SQL ?
-- 244) DIFFERENCES BETWEEN PROJECTION AND SELECTION ?
-- 245) DIFFERENCES BETWEEN WHERE CLAUSE AND HAVING CLAUSE ?
-- 246) DIFFERENCES BETWEEN ALIAS AND DISTINCT ?
-- 247) DIFFERENCES BETWEEN DISTINCT AND UNIQUE ?
-- 248) DIFFERENCES BETWEEN PRIMARY KEY AND FOREIGN KEY ?
-- 249) DIFFERENCES BETWEEN PRIMARY KEY AND UNIQUE ?
-- 250)DIFFERENCES BETWEEN NULL AND NOT NULL ?
-- 251)DIFFERENCES BETWEEN EXPRESSION AND ALIAS ?
-- 252)DIFFERENCES BETWEEN FUNCTIONS AND OPERATORS ?
-- 253)DIFFERENCES BETWEEN USER DEFINED FUNCTION AND BUILT IN FUNCTIONS ?
-- 254)DIFFERENCES BETWEEN SRF AND MRF ?
-- 255)DIFFERENCES BETWEEN SQSR AND MRSQ ?
-- 256)DIFFERENCES BETWEEN SUB QUERY AND JOINS ?
-- 257)DIFFERENCES BETWEEN ALL AND ANY OPERATORS ?
-- 258)DIFFERENCES BETWEEN INNER JOIN TO CARETESIAN JOIN ?
-- 259)DIFFERENCES BETWEEN NATURAL TO INNER JOIN ?
-- 260)DIFFERENCES BETWEEN OUTER JOIN TO INNER JOIN ?
-- 261)DIFFERENCES BETWEEN DELETE AND TRUNCATE ?
-- 262)DIFFERENCES BETWEEN DROP AND DELETE ?
-- 263)DIFFERENCES BETWEEN FLASHBACK AND ROLLBACK ?
-- 264)DIFFERENCES BETWEEN ALTER AND UPDATE ?
-- 265)DIFFERENCES BETWEEN TABLES AND VIEWS ?



-- RULES OF DDL /DML/
-- DDL :
-- 1) CREATE TABLE 
--    RULE 1. THE TABLE NAME /COLUMN_NAME SHOULDN'Y STARTS WITH ANY 
--             NUMBER /SPECIAL CHARACTERS 
--             EX :1EMP / @EMP  ---- IN VALID TABLE_NAME 
--                  EMP1 / EMP@ /E1MP /E@MP ---- VALID TABLE_NAME 
--                  SAME FOR COLUMN_NAME ALSO 
--     RULE 2. THE TABLE_NAME SHOULDN'T REPEATS IN DATABSE 
--     RULE 3. WHILE CREATING TABLE IF WE CREATE PARENT TABLE FIRST AND
--             CHILD TABLE SECOND IT WILL EASY TO CREATE 
     
-- 2) RENAME TABLE 
--     READ THE 1ST RULE OF TABLE_NAME

-- 3) TRUNCATE TABLE 
--    RULE : IF WE ARE TRUNCATING PARENT TABLE ITS NOT POSSIBLE 
--            UNTILL WE REMOVES THE CONNECTION BETWEEN PT AND CT 

-- 4) DROP TABLE 
--     RULE : IF WE WANT TO DROP THE PARENT TABLE WE NEED TO REMEOVE THE CONNECTION THEN WE CAN OTHER TABLE WE CAN DROP EASILY 







-- 5) ALTER : ITS MEANS MODIFICATION OF TABLE 
--      RULE : ALTER COMMAND MOST OF TIME WILL WORKS FOR EMPTY TABLES 
--            EFW COMMANDS IN ALTER WILL WORKS FOR FILLED TABLE 

--     1) ADD COLUMN 
--        RULE : WE CAN ADD COLUMN FOR ANY TABLE IF TABLE IS EMPTY 
--                OR ELSE WE CAN USE NULL CONSTRAINTTO ADD COLUMN 
--               IF WE USE NOT NULL THEN WE CAN ADD COLUMN ONLY EMPTY TABLE 
--      2) DROP COLUMN 
--         THERE IS NO RUELS 
--      3) RENAME COLUMN 
--         COLUMN_NAME RULES WE NEED FOLLOW 
--      4) CHANGE DATATYPE OF COLUMNS 
--         RULE 1 : FOR EMPTY COLUMN WE CAN CHANGE DATATYPES 
--                  IF COLUMN FILLED WITH DATA WE CAN INCREASE THE SIZE OF 
--                  IT BUT WE CANT ABLE CHANGE IT 
--       5) CHANGE NULL TO NOT NULL 
--          RULE1 : FOR PK ITS NOT VALID 
--       6) MAKE PR / FK 
--          RULE FOR PK 1) ONLY ONE PK SHOULD BE PRESENT IN TABLE 
--          RULE FOR FK 1) THE COLUMN SHOULD BE PK IN ANOTHER/ SAME TABLE 
 
--     NOTE FOR ALTER : MOST OF TIME THE ALTER WILL WORK FOR EMPTY                           TABLE   FEW COMMANDS WILL WORK FOR FILLED TABLE












-- DML RULES 
-- 1) INSERT 
--    RULE1 : WE CAN INSERT FOR ANY TABLE BUT WILE INSERTING INTO 
--            CHILD TABLE THE FOREIGN KEY COLUMN VALUE THAT VALUE 
--            SHOULD BE PRESENT IN PARENT TABLE ALSO 

-- 2) DELETE 
--    RULE1 : WE CAN DELETE ANY RECORD FROM THE ANY TABLE BUT 
--            WHILE DELETING RECORDS FROM THE PARENT TABLE WE NEED TO 
--            REMOVE THE CONNECTION ELSE ITS NOT POSSIBLE 

-- 3) UPDATE 
--    RULE1 : WE CAN UPDATE ANY TABLE BUT WHILE UPDATING 
--            THE VALUE OF PARENT TABLE IN THAT THE PK WE
--            NEED TO USE THE VALUES WHICH ARE PRESENT IN CHILD TABLE /NULL  
--            WHERE AS UPDATING THE CHILD TABLE FK VALUE WE NEED 
--            USE THE VALUE WHICH ARE PRESENT IN PARENT TABLE 



















-- Projects 
-- general project in sql 
-- Create a table Customer with the following columns:(parent table)

-- Cid (Primary Key)
-- cname (Customer Name)
-- Mail (Unique Email)
-- Mno (Mobile Number)
-- Dob (Date of Birth)
-- Address (Customer Address)

-- note
-- insert 10 records to customer table make sure 2
-- customers shouldn't associats to any account 

-- Create a table Bank with the following columns:(child table)

-- Bid (Primary Key)
-- Cid (Foreign Key → Customer.Cid, also UNIQUE)
-- Bname (Bank Name)
-- Acno (Unique Account Number)
-- Available_Balance (Decimal Value)

-- note 
-- insert 8 records which matches 8 customer from customer table 
-- Ensure one-to-one relationship between Customer and Bank.











-- Project 2
-- Create table Boys (parent):
-- bid (Primary Key)
-- bname
-- age
-- height
-- type

-- Create table Girls (child):
-- gid (Primary Key)
-- gname
-- age
-- height
-- type
-- bid (Foreign Key → Boys.bid)

-- Insert 6 Boys records.
-- Insert 18 Girls records with these conditions:
-- At least 2 boys should not have any girlfriends.
-- At least 2 girls should not have any boyfriends (their bid should be NULL).
-- Rest should maintain one-to-many (e.g., Boy1 → 4 girls, Boy2 → 3 girls, Boy3 → 5 girls).














-- Project 3 

-- Create a table named Films with the following columns:
-- fid (NUMBER, Primary Key)
-- fname (VARCHAR2(100)) – film name
-- genre (VARCHAR2(50)) – e.g., Action, Comedy
-- release_year (NUMBER(4)) – year of release
-- budget (NUMBER(10)) – film budget

-- Create a table named Actor with the following columns:
-- aid (NUMBER, Primary Key)
-- aname (VARCHAR2(100)) – actor name
-- dob (DATE) – date of birth
-- nationality (VARCHAR2(50))

-- Create a junction table named Film_Actors to represent
-- the many-to-many relationship between Films and Actors.
-- fid references Films(fid)
-- aid references Actors(aid)
-- role_name (VARCHAR2(50)) – character played in the film
-- salary (NUMBER(10)) – actor’s salary for that film



-- note
-- Ensure (fid, aid) is a Composite Primary Key.
-- Insert at least 5 records into the Films table (cover different genres & years).
-- Insert at least 6 records into the Actors table (mix of male/female, different nationalities).
-- insert records into Film_Actors such that:
-- Each film has at least 2 actors.
-- At least 2 actors appear in more than one film.
-- At least 1 actor has a different role_name in different films.
-- No duplicate (fid, aid) combination is allowed.



-- PROJECT4
-- Q1.Create a table BOOK with the following columns:
-- bid (Primary Key, Number)
-- bname (Varchar2(100), Not Null)
-- price (Number with 2 decimals)
-- no_of_pages (Number)
-- published_date (Date)

-- Q2.Create a table AUTHOR with the following columns:
-- aid (Primary Key, Number)
-- aname (Varchar2(100), Not Null)
-- dob (Date)
-- address (Varchar2(200))

-- Q3.Create a junction table BOOK_AUTHOR with columns:
-- bid (Foreign Key references BOOK)
-- aid (Foreign Key references AUTHOR)
-- Make (bid, aid) as a Composite Primary Key.

-- INSERT 7 RECORDS INTO BOOK 
-- INSERT 12 RECORDS INTO AUTHOR 
-- THEN INSERT JUNCTION TABLE THE RECORDS IN 
-- SUCH A WAY THAT MANY TO MANY CONNECTION BETWEEN BOOK TO AUTHOR 
-- 2 RECORDS FROM BOOK TABLE SHOULDN'T CONNECT TO ANY AUTHOR AND 3 AUTHOR 
-- SHOULDN'T CONNECT TO ANY BOOK 


-- 4) Tables:
-- GAME → gid (PK), gname, genre, price
-- PLAYER → pid (PK), pname, level
-- GAME_PLAYER → junction

-- 5) Tables:
-- SONG → sid (PK), sname, duration, album
-- SINGER → sgid (PK), sgname, country
-- SONG_SINGER → junction


-- *Project 5 
-- * Banking System Database

-- *Description:* Design a database to manage customer accounts, transactions, and employee information for a banking system.

-- *Tables:*
-- 1. *Customers*
--     - Customer ID (primary key)
--     - Name
--     - Address
--     - Phone Number
--     - Email
-- 2. *Accounts*
--     - Account ID (primary key)
--     - Customer ID (foreign key)
--     - Account Type (Savings, Current, etc.)
--     - Balance
-- 3. *Transactions*
--     - Transaction ID (primary key)
--     - Account ID (foreign key)
--     - Transaction Type (Deposit, Withdrawal, etc.)
--     - Amount
--     - Date
-- 4. *Employees*
--     - Employee ID (primary key)
--     - Name
--     - Role
--     - Branch ID (foreign key)


-- 5. *Branches*
--     - Branch ID (primary key)
--     - Branch Name
--     - Address

-- 6. *Loans*
--     - Loan ID (primary key)
--     - Customer ID (foreign key)
--     - Loan Amount
--     - Interest Rate
--     - Repayment Term

-- 7. *Credit Cards*
--     - Credit Card ID (primary key)
--     - Customer ID (foreign key)
--     - Card Type
--     - Limit
--     - Expiry Date

-- *Relationships:*
-- - A customer can have multiple accounts (one-to-many).
-- - An account is owned by one customer (many-to-one).
-- - An account can have multiple transactions (one-to-many).
-- - A transaction belongs to one account (many-to-one).
-- - An employee works at one branch (many-to-one).
-- - A branch can have multiple employees (one-to-many).
-- - A customer can have multiple loans and credit cards (one-to-many).









-- Project 6  (for boys )
--  INDIAN PREMIUM LEAGUE 
-- Create Table Questions (Write Structure + Keys + Datatypes)
-- Create a table TEAM to store IPL team details with:
-- team_id (Primary Key)
-- team_name
-- home_city

-- Create a table COACH to store coach details with:
-- coach_id (Primary Key)
-- coach_name
-- experience_years
-- team_id (Foreign Key referencing TEAM table)

-- Create a table PLAYER to store players with:
-- player_id (Primary Key)
-- player_name
-- role (Batsman / Bowler / All-Rounder / Wicket-Keeper)
-- price_crore
-- team_id (Foreign Key referencing TEAM table)

-- Create a table VENUE to store stadium information with:
-- venue_id (Primary Key)
-- stadium_name
-- city
-- capacity

-- Create a table MATCH to store match schedule with:
-- match_id (Primary Key)
-- match_date
-- venue_id (Foreign Key referencing VENUE table)
-- team1_id (Foreign Key referencing TEAM table)
-- team2_id (Foreign Key referencing TEAM table)

-- Create a table PERFORMANCE to store players match performance with:
-- performance_id (Primary Key)
-- match_id (Foreign Key referencing MATCH table)
-- player_id (Foreign Key referencing PLAYER table)
-- runs_scored
-- wickets_taken
-- catches

-- Relationship Summary
-- TEAM → COACH	1 to 1
-- TEAM → PLAYER	1 to M 
-- VENUE → MATCH	1 to M
-- TEAM → MATCH	M to M
-- MATCH → PERFORMANCE	1 to M
-- PLAYER → PERFORMANCE 1 to M	



-- Project 7 ( for girls+ boys )
-- College Fest Event Participation System

-- Create the following tables with suitable data types.
-- Use Primary Keys and Foreign Keys wherever required.

-- Department table 
-- Dept_ID
-- Dept_Name


-- Organizer table 
-- Organizer_ID
-- Organizer_Name
-- Role (Faculty / Student Coordinator)


-- Venue table 
-- Venue_ID
-- Venue_Name
-- Capacity

-- Student table 
-- Student_ID
-- Student_Name
-- Gender
-- Mobile
-- Dept_ID (should refer Dept_ID in Department table)

-- Event table 
-- Event_ID
-- Event_Name
-- Event_Date
-- Organizer_ID (should refer Organizer_ID in Organizer table)
-- Venue_ID (should refer Venue_ID in Venue table)

-- Participation table 
-- Participation_ID
-- Student_ID (should refer Student_ID in Student table)
-- Event_ID (should refer Event_ID in Event table)
-- Position (Winner / Runner / Participant)


-- RELATIONSHIP DETAILS (Wri
-- Department → Student One-to-Many	
-- Organizer → Event One-to-Many
-- Venue → Event  One-to-Many
-- Student → Participation One-to-Many 
-- Event → Participation	One-to-Many	


-- Project 8(12 Tables )
-- ZOMATO DATABASE PROJECT

-- Create a table named RESTAURANT
-- To store restaurant details.
-- Columns:
-- RESTAURANT_ID
-- NAME
-- PHONE
-- EMAIL
-- CITY
-- AREA
-- RATING
-- CREATED_DATE

-- Create a table named CATEGORY
-- To store food categories like "Chinese", "Indian", etc.
-- Columns:
-- CATEGORY_ID
-- CATEGORY_NAME
-- DESCRIPTION

-- Create a table named RESTAURANT_CATEGORY

-- To store which restaurant serves which category (many-to-many relation).
-- Columns:
-- RESTAURANT_ID
-- CATEGORY_ID

-- Create a table named MENU

-- To store each restaurant’s menu information.
-- Columns:
-- MENU_ID
-- RESTAURANT_ID
-- MENU_NAME
-- CREATED_DATE

-- Create a table named MENU_ITEM
-- To store food items under each menu.
-- Columns:
-- ITEM_ID – Primary Key
-- MENU_ID – Foreign Key references MENU
-- ITEM_NAME – Not Null
-- PRICE – Check (PRICE > 0)
-- AVAILABLE_STATUS – Default ‘YES’, Check (Available_Status IN ('YES', 'NO'))

-- Create a table named CUSTOMER
-- To store customer details.
-- Columns:
-- CUSTOMER_ID – Primary Key
-- FULL_NAME – Not Null
-- PHONE – Unique
-- EMAIL – Unique
-- GENDER – Check (Gender IN ('M','F','O'))
-- REGISTRATION_DATE – Default SYSDATE

-- Create a table named ADDRESS
-- To store multiple addresses for each customer.
-- Columns:
-- ADDRESS_ID – Primary Key
-- CUSTOMER_ID – Foreign Key references CUSTOMER
-- HOUSE_NO
-- STREET
-- CITY
-- PINCODE
-- ADDRESS_TYPE – Check (Address_Type IN ('HOME','OFFICE','OTHER’))

-- Create a table named DELIVERY_PERSON
-- To store details of delivery boys.
-- Columns:
-- DELIVERY_ID – Primary Key
-- NAME – Not Null
-- PHONE – Unique
-- VEHICLE_NO
-- STATUS – Default ‘AVAILABLE’, Check (STATUS IN ('AVAILABLE','BUSY'))


-- Create a table named ORDERS
-- To store customer order details.Columns:
-- ORDER_ID – Primary Key
-- CUSTOMER_ID – Foreign Key references CUSTOMER
-- RESTAURANT_ID – Foreign Key references RESTAURANT
-- DELIVERY_ID – Foreign Key references DELIVERY_PERSON
-- ORDER_DATE – Default SYSDATE
-- TOTAL_AMOUNT – Check (TOTAL_AMOUNT >= 0)
-- ORDER_STATUS – Default ‘PLACED’, Check (Order_Status IN ('PLACED','ONWAY','DELIVERED','CANCELLED'))


-- Create a table named ORDER_ITEM
-- To store all items under each order.
-- Columns:
-- ORDER_ID – Foreign Key references ORDERS
-- ITEM_ID – Foreign Key references MENU_ITEM
-- QUANTITY – Check (QUANTITY > 0)
-- PRICE – Check (PRICE > 0)
-- Combination of ORDER_ID and ITEM_ID – Primary Key


-- Create a table named PAYMENT
-- To store payment details for each order.Columns:
-- PAYMENT_ID – Primary Key
-- ORDER_ID – Foreign Key references ORDERS
-- PAYMENT_MODE – Check (Payment_Mode IN ('CARD','CASH','UPI'))
-- PAYMENT_DATE – Default SYSDATE
-- AMOUNT – Check (AMOUNT >= 0)
-- PAYMENT_STATUS – Default ‘PENDING’, Check (Payment_Status IN ('SUCCESS','FAILED','PENDING'))



-- Create a table named REVIEW
-- To store customer reviews for restaurants.
-- Columns:
-- REVIEW_ID – Primary Key
-- CUSTOMER_ID – Foreign Key references CUSTOMER
-- RESTAURANT_ID – Foreign Key references RESTAURANT
-- RATING – Check (Rating BETWEEN 1 AND 5)
-- COMMENTS
-- REVIEW_DATE – Default SYSDATE


-- Relationship 

-- 1)CUSTOMER→ORDERS 1-to-Many
-- 2)RESTAURANT→ORDERS	1-to-Many
-- 3)MENU_CATEGORY→MENU_ITEM 1-to-Many
-- RESTAURANT→MENU_ITEM	1-to-Many
-- ORDERS→ORDER_DETAILS 1-to-Many 
-- MENU_ITEM →ORDER_DETAILS. 1-to-Many
-- ORDERS→PAYMENT  1-to-1
-- DELIVERY_PERSON	→DELIVERY 1-to-Many
-- ORDERS→DELIVERY 1-to-1
-- CUSTOMER→REVIEW 1-to-Many
-- RESTAURANT→REVIEW 1-to-Many
-- COUPON→ORDER_COUPON 1-to-Many



-- Project 9
-- Train Ticket Booking System - SQL


-- 1. TRAIN
-- - TRAIN_ID (PRIMARY KEY)
-- - TRAIN_NAME
-- - SOURCE
-- - DESTINATION
-- - TOTAL_COACHES

-- 2. COACH
-- - COACH_ID (PRIMARY KEY)
-- - TRAIN_ID (FOREIGN KEY → TRAIN.TRAIN_ID)
-- - COACH_TYPE (Sleeper/AC/General)
-- - TOTAL_SEATS

-- 3. PASSENGER
-- - PASSENGER_ID (PRIMARY KEY)
-- - PASSENGER_NAME
-- - GENDER
-- - AGE

-- 4. TICKET
-- - TICKET_ID (PRIMARY KEY)
-- - PASSENGER_ID (FOREIGN KEY → PASSENGER.PASSENGER_ID)
-- - TRAIN_ID (FOREIGN KEY → TRAIN.TRAIN_ID)
-- - BOOKING_DATE
-- - TRAVEL_DATE

-- 5. SEAT_RESERVATION
-- - RES_ID (PRIMARY KEY)
-- - TICKET_ID (FOREIGN KEY → TICKET.TICKET_ID)
-- - COACH_ID (FOREIGN KEY → COACH.COACH_ID)
-- - SEAT_NO
-- - STATUS (Booked/Cancelled)


-- . Relationships
-- - TRAIN → COACH = One-to-Many
-- - TRAIN → TICKET = One-to-Many
-- - PASSENGER → TICKET = One-to-Many
-- - TICKET → SEAT_RESERVATION = One-to-Many
-- - COACH → SEAT_RESERVATION = One-to-Many


--  Indexes
-- CREATE INDEX On  (TRAIN_NAME);
-- CREATE INDEX on (PASSENGER_NAME)
-- CREATE INDEX ON TICKET(TRAVEL_DATE);

	
